// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pipelined_layer_processor_read_big_tile_Pipeline_Read_Loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        sext_ln15_2_i,
        tile_A_V_address1,
        tile_A_V_ce1,
        tile_A_V_we1,
        tile_A_V_d1,
        tile_A_V_1_address1,
        tile_A_V_1_ce1,
        tile_A_V_1_we1,
        tile_A_V_1_d1,
        tile_A_V_2_address1,
        tile_A_V_2_ce1,
        tile_A_V_2_we1,
        tile_A_V_2_d1,
        tile_A_V_3_address1,
        tile_A_V_3_ce1,
        tile_A_V_3_we1,
        tile_A_V_3_d1,
        tile_A_V_4_address1,
        tile_A_V_4_ce1,
        tile_A_V_4_we1,
        tile_A_V_4_d1,
        tile_A_V_5_address1,
        tile_A_V_5_ce1,
        tile_A_V_5_we1,
        tile_A_V_5_d1,
        tile_A_V_6_address1,
        tile_A_V_6_ce1,
        tile_A_V_6_we1,
        tile_A_V_6_d1,
        tile_A_V_7_address1,
        tile_A_V_7_ce1,
        tile_A_V_7_we1,
        tile_A_V_7_d1,
        tile_A_V_8_address1,
        tile_A_V_8_ce1,
        tile_A_V_8_we1,
        tile_A_V_8_d1,
        tile_A_V_9_address1,
        tile_A_V_9_ce1,
        tile_A_V_9_we1,
        tile_A_V_9_d1,
        tile_A_V_10_address1,
        tile_A_V_10_ce1,
        tile_A_V_10_we1,
        tile_A_V_10_d1,
        tile_A_V_11_address1,
        tile_A_V_11_ce1,
        tile_A_V_11_we1,
        tile_A_V_11_d1,
        tile_A_V_12_address1,
        tile_A_V_12_ce1,
        tile_A_V_12_we1,
        tile_A_V_12_d1,
        tile_A_V_13_address1,
        tile_A_V_13_ce1,
        tile_A_V_13_we1,
        tile_A_V_13_d1,
        tile_A_V_14_address1,
        tile_A_V_14_ce1,
        tile_A_V_14_we1,
        tile_A_V_14_d1,
        tile_A_V_15_address1,
        tile_A_V_15_ce1,
        tile_A_V_15_we1,
        tile_A_V_15_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [255:0] m_axi_gmem0_WDATA;
output  [31:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [255:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [58:0] sext_ln15_2_i;
output  [0:0] tile_A_V_address1;
output   tile_A_V_ce1;
output   tile_A_V_we1;
output  [255:0] tile_A_V_d1;
output  [0:0] tile_A_V_1_address1;
output   tile_A_V_1_ce1;
output   tile_A_V_1_we1;
output  [255:0] tile_A_V_1_d1;
output  [0:0] tile_A_V_2_address1;
output   tile_A_V_2_ce1;
output   tile_A_V_2_we1;
output  [255:0] tile_A_V_2_d1;
output  [0:0] tile_A_V_3_address1;
output   tile_A_V_3_ce1;
output   tile_A_V_3_we1;
output  [255:0] tile_A_V_3_d1;
output  [0:0] tile_A_V_4_address1;
output   tile_A_V_4_ce1;
output   tile_A_V_4_we1;
output  [255:0] tile_A_V_4_d1;
output  [0:0] tile_A_V_5_address1;
output   tile_A_V_5_ce1;
output   tile_A_V_5_we1;
output  [255:0] tile_A_V_5_d1;
output  [0:0] tile_A_V_6_address1;
output   tile_A_V_6_ce1;
output   tile_A_V_6_we1;
output  [255:0] tile_A_V_6_d1;
output  [0:0] tile_A_V_7_address1;
output   tile_A_V_7_ce1;
output   tile_A_V_7_we1;
output  [255:0] tile_A_V_7_d1;
output  [0:0] tile_A_V_8_address1;
output   tile_A_V_8_ce1;
output   tile_A_V_8_we1;
output  [255:0] tile_A_V_8_d1;
output  [0:0] tile_A_V_9_address1;
output   tile_A_V_9_ce1;
output   tile_A_V_9_we1;
output  [255:0] tile_A_V_9_d1;
output  [0:0] tile_A_V_10_address1;
output   tile_A_V_10_ce1;
output   tile_A_V_10_we1;
output  [255:0] tile_A_V_10_d1;
output  [0:0] tile_A_V_11_address1;
output   tile_A_V_11_ce1;
output   tile_A_V_11_we1;
output  [255:0] tile_A_V_11_d1;
output  [0:0] tile_A_V_12_address1;
output   tile_A_V_12_ce1;
output   tile_A_V_12_we1;
output  [255:0] tile_A_V_12_d1;
output  [0:0] tile_A_V_13_address1;
output   tile_A_V_13_ce1;
output   tile_A_V_13_we1;
output  [255:0] tile_A_V_13_d1;
output  [0:0] tile_A_V_14_address1;
output   tile_A_V_14_ce1;
output   tile_A_V_14_we1;
output  [255:0] tile_A_V_14_d1;
output  [0:0] tile_A_V_15_address1;
output   tile_A_V_15_ce1;
output   tile_A_V_15_we1;
output  [255:0] tile_A_V_15_d1;

reg ap_idle;
reg m_axi_gmem0_RREADY;
reg tile_A_V_ce1;
reg tile_A_V_we1;
reg tile_A_V_1_ce1;
reg tile_A_V_1_we1;
reg tile_A_V_2_ce1;
reg tile_A_V_2_we1;
reg tile_A_V_3_ce1;
reg tile_A_V_3_we1;
reg tile_A_V_4_ce1;
reg tile_A_V_4_we1;
reg tile_A_V_5_ce1;
reg tile_A_V_5_we1;
reg tile_A_V_6_ce1;
reg tile_A_V_6_we1;
reg tile_A_V_7_ce1;
reg tile_A_V_7_we1;
reg tile_A_V_8_ce1;
reg tile_A_V_8_we1;
reg tile_A_V_9_ce1;
reg tile_A_V_9_we1;
reg tile_A_V_10_ce1;
reg tile_A_V_10_we1;
reg tile_A_V_11_ce1;
reg tile_A_V_11_we1;
reg tile_A_V_12_ce1;
reg tile_A_V_12_we1;
reg tile_A_V_13_ce1;
reg tile_A_V_13_we1;
reg tile_A_V_14_ce1;
reg tile_A_V_14_we1;
reg tile_A_V_15_ce1;
reg tile_A_V_15_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln15_reg_485;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln15_fu_419_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_reg_489;
reg   [0:0] tmp_reg_489_pp0_iter1_reg;
wire   [3:0] trunc_ln22_fu_439_p1;
reg   [3:0] trunc_ln22_reg_494;
reg   [3:0] trunc_ln22_reg_494_pp0_iter1_reg;
reg   [255:0] p_Val2_s_reg_498;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln22_fu_454_p1;
reg   [5:0] i_fu_120;
wire   [5:0] add_ln15_fu_425_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i_1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

pipelined_layer_processor_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln15_fu_419_p2 == 1'd0))) begin
            i_fu_120 <= add_ln15_fu_425_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_120 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln15_reg_485 <= icmp_ln15_fu_419_p2;
        tmp_reg_489_pp0_iter1_reg <= tmp_reg_489;
        trunc_ln22_reg_494_pp0_iter1_reg <= trunc_ln22_reg_494;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln15_reg_485 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Val2_s_reg_498 <= m_axi_gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln15_fu_419_p2 == 1'd0))) begin
        tmp_reg_489 <= ap_sig_allocacmp_i_1[32'd4];
        trunc_ln22_reg_494 <= trunc_ln22_fu_439_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln15_fu_419_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln15_reg_485 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_120;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln15_reg_485 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln15_reg_485 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_10_ce1 = 1'b1;
    end else begin
        tile_A_V_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd10))) begin
        tile_A_V_10_we1 = 1'b1;
    end else begin
        tile_A_V_10_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_11_ce1 = 1'b1;
    end else begin
        tile_A_V_11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd11))) begin
        tile_A_V_11_we1 = 1'b1;
    end else begin
        tile_A_V_11_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_12_ce1 = 1'b1;
    end else begin
        tile_A_V_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd12))) begin
        tile_A_V_12_we1 = 1'b1;
    end else begin
        tile_A_V_12_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_13_ce1 = 1'b1;
    end else begin
        tile_A_V_13_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd13))) begin
        tile_A_V_13_we1 = 1'b1;
    end else begin
        tile_A_V_13_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_14_ce1 = 1'b1;
    end else begin
        tile_A_V_14_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd14))) begin
        tile_A_V_14_we1 = 1'b1;
    end else begin
        tile_A_V_14_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_15_ce1 = 1'b1;
    end else begin
        tile_A_V_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd15))) begin
        tile_A_V_15_we1 = 1'b1;
    end else begin
        tile_A_V_15_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_1_ce1 = 1'b1;
    end else begin
        tile_A_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd1))) begin
        tile_A_V_1_we1 = 1'b1;
    end else begin
        tile_A_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_2_ce1 = 1'b1;
    end else begin
        tile_A_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd2))) begin
        tile_A_V_2_we1 = 1'b1;
    end else begin
        tile_A_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_3_ce1 = 1'b1;
    end else begin
        tile_A_V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd3))) begin
        tile_A_V_3_we1 = 1'b1;
    end else begin
        tile_A_V_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_4_ce1 = 1'b1;
    end else begin
        tile_A_V_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd4))) begin
        tile_A_V_4_we1 = 1'b1;
    end else begin
        tile_A_V_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_5_ce1 = 1'b1;
    end else begin
        tile_A_V_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd5))) begin
        tile_A_V_5_we1 = 1'b1;
    end else begin
        tile_A_V_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_6_ce1 = 1'b1;
    end else begin
        tile_A_V_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd6))) begin
        tile_A_V_6_we1 = 1'b1;
    end else begin
        tile_A_V_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_7_ce1 = 1'b1;
    end else begin
        tile_A_V_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd7))) begin
        tile_A_V_7_we1 = 1'b1;
    end else begin
        tile_A_V_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_8_ce1 = 1'b1;
    end else begin
        tile_A_V_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd8))) begin
        tile_A_V_8_we1 = 1'b1;
    end else begin
        tile_A_V_8_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_9_ce1 = 1'b1;
    end else begin
        tile_A_V_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd9))) begin
        tile_A_V_9_we1 = 1'b1;
    end else begin
        tile_A_V_9_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tile_A_V_ce1 = 1'b1;
    end else begin
        tile_A_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln22_reg_494_pp0_iter1_reg == 4'd0))) begin
        tile_A_V_we1 = 1'b1;
    end else begin
        tile_A_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15_fu_425_p2 = (ap_sig_allocacmp_i_1 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((icmp_ln15_reg_485 == 1'd0) & (m_axi_gmem0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((icmp_ln15_reg_485 == 1'd0) & (m_axi_gmem0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln15_reg_485 == 1'd0) & (m_axi_gmem0_RVALID == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln15_fu_419_p2 = ((ap_sig_allocacmp_i_1 == 6'd32) ? 1'b1 : 1'b0);

assign m_axi_gmem0_ARADDR = 64'd0;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 32'd0;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_ARVALID = 1'b0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 256'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 32'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign tile_A_V_10_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_10_d1 = p_Val2_s_reg_498;

assign tile_A_V_11_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_11_d1 = p_Val2_s_reg_498;

assign tile_A_V_12_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_12_d1 = p_Val2_s_reg_498;

assign tile_A_V_13_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_13_d1 = p_Val2_s_reg_498;

assign tile_A_V_14_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_14_d1 = p_Val2_s_reg_498;

assign tile_A_V_15_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_15_d1 = p_Val2_s_reg_498;

assign tile_A_V_1_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_1_d1 = p_Val2_s_reg_498;

assign tile_A_V_2_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_2_d1 = p_Val2_s_reg_498;

assign tile_A_V_3_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_3_d1 = p_Val2_s_reg_498;

assign tile_A_V_4_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_4_d1 = p_Val2_s_reg_498;

assign tile_A_V_5_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_5_d1 = p_Val2_s_reg_498;

assign tile_A_V_6_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_6_d1 = p_Val2_s_reg_498;

assign tile_A_V_7_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_7_d1 = p_Val2_s_reg_498;

assign tile_A_V_8_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_8_d1 = p_Val2_s_reg_498;

assign tile_A_V_9_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_9_d1 = p_Val2_s_reg_498;

assign tile_A_V_address1 = zext_ln22_fu_454_p1;

assign tile_A_V_d1 = p_Val2_s_reg_498;

assign trunc_ln22_fu_439_p1 = ap_sig_allocacmp_i_1[3:0];

assign zext_ln22_fu_454_p1 = tmp_reg_489_pp0_iter1_reg;

endmodule //pipelined_layer_processor_read_big_tile_Pipeline_Read_Loop
