// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pipelined_layer_processor_dataflow_parent_loop_proc (
        num_depth_tiles,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        mat_A,
        i,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        mat_B,
        num_col_tiles,
        j,
        tile_C_V_address0,
        tile_C_V_ce0,
        tile_C_V_d0,
        tile_C_V_q0,
        tile_C_V_we0,
        tile_C_V_address1,
        tile_C_V_ce1,
        tile_C_V_d1,
        tile_C_V_q1,
        tile_C_V_we1,
        tile_C_V_1_address0,
        tile_C_V_1_ce0,
        tile_C_V_1_d0,
        tile_C_V_1_q0,
        tile_C_V_1_we0,
        tile_C_V_1_address1,
        tile_C_V_1_ce1,
        tile_C_V_1_d1,
        tile_C_V_1_q1,
        tile_C_V_1_we1,
        tile_C_V_2_address0,
        tile_C_V_2_ce0,
        tile_C_V_2_d0,
        tile_C_V_2_q0,
        tile_C_V_2_we0,
        tile_C_V_2_address1,
        tile_C_V_2_ce1,
        tile_C_V_2_d1,
        tile_C_V_2_q1,
        tile_C_V_2_we1,
        tile_C_V_3_address0,
        tile_C_V_3_ce0,
        tile_C_V_3_d0,
        tile_C_V_3_q0,
        tile_C_V_3_we0,
        tile_C_V_3_address1,
        tile_C_V_3_ce1,
        tile_C_V_3_d1,
        tile_C_V_3_q1,
        tile_C_V_3_we1,
        tile_C_V_4_address0,
        tile_C_V_4_ce0,
        tile_C_V_4_d0,
        tile_C_V_4_q0,
        tile_C_V_4_we0,
        tile_C_V_4_address1,
        tile_C_V_4_ce1,
        tile_C_V_4_d1,
        tile_C_V_4_q1,
        tile_C_V_4_we1,
        tile_C_V_5_address0,
        tile_C_V_5_ce0,
        tile_C_V_5_d0,
        tile_C_V_5_q0,
        tile_C_V_5_we0,
        tile_C_V_5_address1,
        tile_C_V_5_ce1,
        tile_C_V_5_d1,
        tile_C_V_5_q1,
        tile_C_V_5_we1,
        tile_C_V_6_address0,
        tile_C_V_6_ce0,
        tile_C_V_6_d0,
        tile_C_V_6_q0,
        tile_C_V_6_we0,
        tile_C_V_6_address1,
        tile_C_V_6_ce1,
        tile_C_V_6_d1,
        tile_C_V_6_q1,
        tile_C_V_6_we1,
        tile_C_V_7_address0,
        tile_C_V_7_ce0,
        tile_C_V_7_d0,
        tile_C_V_7_q0,
        tile_C_V_7_we0,
        tile_C_V_7_address1,
        tile_C_V_7_ce1,
        tile_C_V_7_d1,
        tile_C_V_7_q1,
        tile_C_V_7_we1,
        tile_C_V_8_address0,
        tile_C_V_8_ce0,
        tile_C_V_8_d0,
        tile_C_V_8_q0,
        tile_C_V_8_we0,
        tile_C_V_8_address1,
        tile_C_V_8_ce1,
        tile_C_V_8_d1,
        tile_C_V_8_q1,
        tile_C_V_8_we1,
        tile_C_V_9_address0,
        tile_C_V_9_ce0,
        tile_C_V_9_d0,
        tile_C_V_9_q0,
        tile_C_V_9_we0,
        tile_C_V_9_address1,
        tile_C_V_9_ce1,
        tile_C_V_9_d1,
        tile_C_V_9_q1,
        tile_C_V_9_we1,
        tile_C_V_10_address0,
        tile_C_V_10_ce0,
        tile_C_V_10_d0,
        tile_C_V_10_q0,
        tile_C_V_10_we0,
        tile_C_V_10_address1,
        tile_C_V_10_ce1,
        tile_C_V_10_d1,
        tile_C_V_10_q1,
        tile_C_V_10_we1,
        tile_C_V_11_address0,
        tile_C_V_11_ce0,
        tile_C_V_11_d0,
        tile_C_V_11_q0,
        tile_C_V_11_we0,
        tile_C_V_11_address1,
        tile_C_V_11_ce1,
        tile_C_V_11_d1,
        tile_C_V_11_q1,
        tile_C_V_11_we1,
        tile_C_V_12_address0,
        tile_C_V_12_ce0,
        tile_C_V_12_d0,
        tile_C_V_12_q0,
        tile_C_V_12_we0,
        tile_C_V_12_address1,
        tile_C_V_12_ce1,
        tile_C_V_12_d1,
        tile_C_V_12_q1,
        tile_C_V_12_we1,
        tile_C_V_13_address0,
        tile_C_V_13_ce0,
        tile_C_V_13_d0,
        tile_C_V_13_q0,
        tile_C_V_13_we0,
        tile_C_V_13_address1,
        tile_C_V_13_ce1,
        tile_C_V_13_d1,
        tile_C_V_13_q1,
        tile_C_V_13_we1,
        tile_C_V_14_address0,
        tile_C_V_14_ce0,
        tile_C_V_14_d0,
        tile_C_V_14_q0,
        tile_C_V_14_we0,
        tile_C_V_14_address1,
        tile_C_V_14_ce1,
        tile_C_V_14_d1,
        tile_C_V_14_q1,
        tile_C_V_14_we1,
        tile_C_V_15_address0,
        tile_C_V_15_ce0,
        tile_C_V_15_d0,
        tile_C_V_15_q0,
        tile_C_V_15_we0,
        tile_C_V_15_address1,
        tile_C_V_15_ce1,
        tile_C_V_15_d1,
        tile_C_V_15_q1,
        tile_C_V_15_we1,
        ap_clk,
        ap_rst,
        mat_A_ap_vld,
        i_ap_vld,
        num_depth_tiles_ap_vld,
        mat_B_ap_vld,
        num_col_tiles_ap_vld,
        j_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] num_depth_tiles;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [255:0] m_axi_gmem0_WDATA;
output  [31:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [255:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [63:0] mat_A;
input  [26:0] i;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [255:0] m_axi_gmem1_WDATA;
output  [31:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [255:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] mat_B;
input  [26:0] num_col_tiles;
input  [26:0] j;
output  [5:0] tile_C_V_address0;
output   tile_C_V_ce0;
output  [31:0] tile_C_V_d0;
input  [31:0] tile_C_V_q0;
output   tile_C_V_we0;
output  [5:0] tile_C_V_address1;
output   tile_C_V_ce1;
output  [31:0] tile_C_V_d1;
input  [31:0] tile_C_V_q1;
output   tile_C_V_we1;
output  [5:0] tile_C_V_1_address0;
output   tile_C_V_1_ce0;
output  [31:0] tile_C_V_1_d0;
input  [31:0] tile_C_V_1_q0;
output   tile_C_V_1_we0;
output  [5:0] tile_C_V_1_address1;
output   tile_C_V_1_ce1;
output  [31:0] tile_C_V_1_d1;
input  [31:0] tile_C_V_1_q1;
output   tile_C_V_1_we1;
output  [5:0] tile_C_V_2_address0;
output   tile_C_V_2_ce0;
output  [31:0] tile_C_V_2_d0;
input  [31:0] tile_C_V_2_q0;
output   tile_C_V_2_we0;
output  [5:0] tile_C_V_2_address1;
output   tile_C_V_2_ce1;
output  [31:0] tile_C_V_2_d1;
input  [31:0] tile_C_V_2_q1;
output   tile_C_V_2_we1;
output  [5:0] tile_C_V_3_address0;
output   tile_C_V_3_ce0;
output  [31:0] tile_C_V_3_d0;
input  [31:0] tile_C_V_3_q0;
output   tile_C_V_3_we0;
output  [5:0] tile_C_V_3_address1;
output   tile_C_V_3_ce1;
output  [31:0] tile_C_V_3_d1;
input  [31:0] tile_C_V_3_q1;
output   tile_C_V_3_we1;
output  [5:0] tile_C_V_4_address0;
output   tile_C_V_4_ce0;
output  [31:0] tile_C_V_4_d0;
input  [31:0] tile_C_V_4_q0;
output   tile_C_V_4_we0;
output  [5:0] tile_C_V_4_address1;
output   tile_C_V_4_ce1;
output  [31:0] tile_C_V_4_d1;
input  [31:0] tile_C_V_4_q1;
output   tile_C_V_4_we1;
output  [5:0] tile_C_V_5_address0;
output   tile_C_V_5_ce0;
output  [31:0] tile_C_V_5_d0;
input  [31:0] tile_C_V_5_q0;
output   tile_C_V_5_we0;
output  [5:0] tile_C_V_5_address1;
output   tile_C_V_5_ce1;
output  [31:0] tile_C_V_5_d1;
input  [31:0] tile_C_V_5_q1;
output   tile_C_V_5_we1;
output  [5:0] tile_C_V_6_address0;
output   tile_C_V_6_ce0;
output  [31:0] tile_C_V_6_d0;
input  [31:0] tile_C_V_6_q0;
output   tile_C_V_6_we0;
output  [5:0] tile_C_V_6_address1;
output   tile_C_V_6_ce1;
output  [31:0] tile_C_V_6_d1;
input  [31:0] tile_C_V_6_q1;
output   tile_C_V_6_we1;
output  [5:0] tile_C_V_7_address0;
output   tile_C_V_7_ce0;
output  [31:0] tile_C_V_7_d0;
input  [31:0] tile_C_V_7_q0;
output   tile_C_V_7_we0;
output  [5:0] tile_C_V_7_address1;
output   tile_C_V_7_ce1;
output  [31:0] tile_C_V_7_d1;
input  [31:0] tile_C_V_7_q1;
output   tile_C_V_7_we1;
output  [5:0] tile_C_V_8_address0;
output   tile_C_V_8_ce0;
output  [31:0] tile_C_V_8_d0;
input  [31:0] tile_C_V_8_q0;
output   tile_C_V_8_we0;
output  [5:0] tile_C_V_8_address1;
output   tile_C_V_8_ce1;
output  [31:0] tile_C_V_8_d1;
input  [31:0] tile_C_V_8_q1;
output   tile_C_V_8_we1;
output  [5:0] tile_C_V_9_address0;
output   tile_C_V_9_ce0;
output  [31:0] tile_C_V_9_d0;
input  [31:0] tile_C_V_9_q0;
output   tile_C_V_9_we0;
output  [5:0] tile_C_V_9_address1;
output   tile_C_V_9_ce1;
output  [31:0] tile_C_V_9_d1;
input  [31:0] tile_C_V_9_q1;
output   tile_C_V_9_we1;
output  [5:0] tile_C_V_10_address0;
output   tile_C_V_10_ce0;
output  [31:0] tile_C_V_10_d0;
input  [31:0] tile_C_V_10_q0;
output   tile_C_V_10_we0;
output  [5:0] tile_C_V_10_address1;
output   tile_C_V_10_ce1;
output  [31:0] tile_C_V_10_d1;
input  [31:0] tile_C_V_10_q1;
output   tile_C_V_10_we1;
output  [5:0] tile_C_V_11_address0;
output   tile_C_V_11_ce0;
output  [31:0] tile_C_V_11_d0;
input  [31:0] tile_C_V_11_q0;
output   tile_C_V_11_we0;
output  [5:0] tile_C_V_11_address1;
output   tile_C_V_11_ce1;
output  [31:0] tile_C_V_11_d1;
input  [31:0] tile_C_V_11_q1;
output   tile_C_V_11_we1;
output  [5:0] tile_C_V_12_address0;
output   tile_C_V_12_ce0;
output  [31:0] tile_C_V_12_d0;
input  [31:0] tile_C_V_12_q0;
output   tile_C_V_12_we0;
output  [5:0] tile_C_V_12_address1;
output   tile_C_V_12_ce1;
output  [31:0] tile_C_V_12_d1;
input  [31:0] tile_C_V_12_q1;
output   tile_C_V_12_we1;
output  [5:0] tile_C_V_13_address0;
output   tile_C_V_13_ce0;
output  [31:0] tile_C_V_13_d0;
input  [31:0] tile_C_V_13_q0;
output   tile_C_V_13_we0;
output  [5:0] tile_C_V_13_address1;
output   tile_C_V_13_ce1;
output  [31:0] tile_C_V_13_d1;
input  [31:0] tile_C_V_13_q1;
output   tile_C_V_13_we1;
output  [5:0] tile_C_V_14_address0;
output   tile_C_V_14_ce0;
output  [31:0] tile_C_V_14_d0;
input  [31:0] tile_C_V_14_q0;
output   tile_C_V_14_we0;
output  [5:0] tile_C_V_14_address1;
output   tile_C_V_14_ce1;
output  [31:0] tile_C_V_14_d1;
input  [31:0] tile_C_V_14_q1;
output   tile_C_V_14_we1;
output  [5:0] tile_C_V_15_address0;
output   tile_C_V_15_ce0;
output  [31:0] tile_C_V_15_d0;
input  [31:0] tile_C_V_15_q0;
output   tile_C_V_15_we0;
output  [5:0] tile_C_V_15_address1;
output   tile_C_V_15_ce1;
output  [31:0] tile_C_V_15_d1;
input  [31:0] tile_C_V_15_q1;
output   tile_C_V_15_we1;
input   ap_clk;
input   ap_rst;
input   mat_A_ap_vld;
input   i_ap_vld;
input   num_depth_tiles_ap_vld;
input   mat_B_ap_vld;
input   num_col_tiles_ap_vld;
input   j_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg ap_done;
reg ap_ready;
reg ap_idle;

wire    dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWVALID;
wire   [63:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWADDR;
wire   [0:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWID;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWLEN;
wire   [2:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWBURST;
wire   [1:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWPROT;
wire   [3:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWQOS;
wire   [3:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWREGION;
wire   [0:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWUSER;
wire    dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_WVALID;
wire   [255:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_WDATA;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_WSTRB;
wire    dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_WLAST;
wire   [0:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_WID;
wire   [0:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_WUSER;
wire    dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARVALID;
wire   [63:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARADDR;
wire   [0:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARID;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARLEN;
wire   [2:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARBURST;
wire   [1:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARPROT;
wire   [3:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARQOS;
wire   [3:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARREGION;
wire   [0:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARUSER;
wire    dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_RREADY;
wire    dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_BREADY;
wire   [30:0] dataflow_in_loop_Depth_Loop_U0_k;
wire   [26:0] dataflow_in_loop_Depth_Loop_U0_num_depth_tiles;
wire    dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWVALID;
wire   [63:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWADDR;
wire   [0:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWID;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWLEN;
wire   [2:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWBURST;
wire   [1:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWPROT;
wire   [3:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWQOS;
wire   [3:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWREGION;
wire   [0:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWUSER;
wire    dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_WVALID;
wire   [255:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_WDATA;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_WSTRB;
wire    dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_WLAST;
wire   [0:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_WID;
wire   [0:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_WUSER;
wire    dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARVALID;
wire   [63:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARADDR;
wire   [0:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARID;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARLEN;
wire   [2:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARBURST;
wire   [1:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARPROT;
wire   [3:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARQOS;
wire   [3:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARREGION;
wire   [0:0] dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARUSER;
wire    dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_RREADY;
wire    dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_BREADY;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_we1;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_address0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_ce0;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_d0;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_we0;
wire   [5:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_address1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_ce1;
wire   [31:0] dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_d1;
wire    dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_we1;
wire    dataflow_in_loop_Depth_Loop_U0_ap_start;
wire    dataflow_in_loop_Depth_Loop_U0_ap_done;
wire    dataflow_in_loop_Depth_Loop_U0_ap_ready;
wire    dataflow_in_loop_Depth_Loop_U0_ap_idle;
reg    dataflow_in_loop_Depth_Loop_U0_ap_continue;
reg   [31:0] loop_dataflow_input_count;
reg   [31:0] loop_dataflow_output_count;
wire   [31:0] bound_minus_1;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 loop_dataflow_input_count = 32'd0;
#0 loop_dataflow_output_count = 32'd0;
end

pipelined_layer_processor_dataflow_in_loop_Depth_Loop dataflow_in_loop_Depth_Loop_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .m_axi_gmem0_AWVALID(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(m_axi_gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(m_axi_gmem0_RVALID),
    .m_axi_gmem0_RREADY(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(m_axi_gmem0_RDATA),
    .m_axi_gmem0_RLAST(m_axi_gmem0_RLAST),
    .m_axi_gmem0_RID(m_axi_gmem0_RID),
    .m_axi_gmem0_RFIFONUM(m_axi_gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(m_axi_gmem0_RUSER),
    .m_axi_gmem0_RRESP(m_axi_gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .mat_A(mat_A),
    .k(dataflow_in_loop_Depth_Loop_U0_k),
    .i(i),
    .num_depth_tiles(dataflow_in_loop_Depth_Loop_U0_num_depth_tiles),
    .m_axi_gmem1_AWVALID(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(m_axi_gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(m_axi_gmem1_RVALID),
    .m_axi_gmem1_RREADY(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(m_axi_gmem1_RDATA),
    .m_axi_gmem1_RLAST(m_axi_gmem1_RLAST),
    .m_axi_gmem1_RID(m_axi_gmem1_RID),
    .m_axi_gmem1_RFIFONUM(m_axi_gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(m_axi_gmem1_RUSER),
    .m_axi_gmem1_RRESP(m_axi_gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .mat_B(mat_B),
    .num_col_tiles(num_col_tiles),
    .j(j),
    .tile_C_V_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_address0),
    .tile_C_V_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_ce0),
    .tile_C_V_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_d0),
    .tile_C_V_q0(tile_C_V_q0),
    .tile_C_V_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_we0),
    .tile_C_V_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_address1),
    .tile_C_V_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_ce1),
    .tile_C_V_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_d1),
    .tile_C_V_q1(32'd0),
    .tile_C_V_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_we1),
    .tile_C_V_1_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_address0),
    .tile_C_V_1_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_ce0),
    .tile_C_V_1_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_d0),
    .tile_C_V_1_q0(tile_C_V_1_q0),
    .tile_C_V_1_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_we0),
    .tile_C_V_1_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_address1),
    .tile_C_V_1_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_ce1),
    .tile_C_V_1_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_d1),
    .tile_C_V_1_q1(32'd0),
    .tile_C_V_1_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_we1),
    .tile_C_V_2_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_address0),
    .tile_C_V_2_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_ce0),
    .tile_C_V_2_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_d0),
    .tile_C_V_2_q0(tile_C_V_2_q0),
    .tile_C_V_2_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_we0),
    .tile_C_V_2_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_address1),
    .tile_C_V_2_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_ce1),
    .tile_C_V_2_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_d1),
    .tile_C_V_2_q1(32'd0),
    .tile_C_V_2_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_we1),
    .tile_C_V_3_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_address0),
    .tile_C_V_3_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_ce0),
    .tile_C_V_3_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_d0),
    .tile_C_V_3_q0(tile_C_V_3_q0),
    .tile_C_V_3_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_we0),
    .tile_C_V_3_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_address1),
    .tile_C_V_3_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_ce1),
    .tile_C_V_3_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_d1),
    .tile_C_V_3_q1(32'd0),
    .tile_C_V_3_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_we1),
    .tile_C_V_4_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_address0),
    .tile_C_V_4_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_ce0),
    .tile_C_V_4_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_d0),
    .tile_C_V_4_q0(tile_C_V_4_q0),
    .tile_C_V_4_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_we0),
    .tile_C_V_4_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_address1),
    .tile_C_V_4_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_ce1),
    .tile_C_V_4_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_d1),
    .tile_C_V_4_q1(32'd0),
    .tile_C_V_4_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_we1),
    .tile_C_V_5_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_address0),
    .tile_C_V_5_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_ce0),
    .tile_C_V_5_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_d0),
    .tile_C_V_5_q0(tile_C_V_5_q0),
    .tile_C_V_5_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_we0),
    .tile_C_V_5_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_address1),
    .tile_C_V_5_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_ce1),
    .tile_C_V_5_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_d1),
    .tile_C_V_5_q1(32'd0),
    .tile_C_V_5_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_we1),
    .tile_C_V_6_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_address0),
    .tile_C_V_6_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_ce0),
    .tile_C_V_6_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_d0),
    .tile_C_V_6_q0(tile_C_V_6_q0),
    .tile_C_V_6_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_we0),
    .tile_C_V_6_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_address1),
    .tile_C_V_6_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_ce1),
    .tile_C_V_6_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_d1),
    .tile_C_V_6_q1(32'd0),
    .tile_C_V_6_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_we1),
    .tile_C_V_7_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_address0),
    .tile_C_V_7_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_ce0),
    .tile_C_V_7_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_d0),
    .tile_C_V_7_q0(tile_C_V_7_q0),
    .tile_C_V_7_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_we0),
    .tile_C_V_7_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_address1),
    .tile_C_V_7_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_ce1),
    .tile_C_V_7_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_d1),
    .tile_C_V_7_q1(32'd0),
    .tile_C_V_7_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_we1),
    .tile_C_V_8_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_address0),
    .tile_C_V_8_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_ce0),
    .tile_C_V_8_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_d0),
    .tile_C_V_8_q0(tile_C_V_8_q0),
    .tile_C_V_8_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_we0),
    .tile_C_V_8_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_address1),
    .tile_C_V_8_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_ce1),
    .tile_C_V_8_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_d1),
    .tile_C_V_8_q1(32'd0),
    .tile_C_V_8_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_we1),
    .tile_C_V_9_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_address0),
    .tile_C_V_9_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_ce0),
    .tile_C_V_9_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_d0),
    .tile_C_V_9_q0(tile_C_V_9_q0),
    .tile_C_V_9_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_we0),
    .tile_C_V_9_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_address1),
    .tile_C_V_9_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_ce1),
    .tile_C_V_9_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_d1),
    .tile_C_V_9_q1(32'd0),
    .tile_C_V_9_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_we1),
    .tile_C_V_10_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_address0),
    .tile_C_V_10_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_ce0),
    .tile_C_V_10_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_d0),
    .tile_C_V_10_q0(tile_C_V_10_q0),
    .tile_C_V_10_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_we0),
    .tile_C_V_10_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_address1),
    .tile_C_V_10_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_ce1),
    .tile_C_V_10_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_d1),
    .tile_C_V_10_q1(32'd0),
    .tile_C_V_10_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_we1),
    .tile_C_V_11_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_address0),
    .tile_C_V_11_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_ce0),
    .tile_C_V_11_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_d0),
    .tile_C_V_11_q0(tile_C_V_11_q0),
    .tile_C_V_11_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_we0),
    .tile_C_V_11_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_address1),
    .tile_C_V_11_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_ce1),
    .tile_C_V_11_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_d1),
    .tile_C_V_11_q1(32'd0),
    .tile_C_V_11_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_we1),
    .tile_C_V_12_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_address0),
    .tile_C_V_12_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_ce0),
    .tile_C_V_12_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_d0),
    .tile_C_V_12_q0(tile_C_V_12_q0),
    .tile_C_V_12_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_we0),
    .tile_C_V_12_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_address1),
    .tile_C_V_12_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_ce1),
    .tile_C_V_12_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_d1),
    .tile_C_V_12_q1(32'd0),
    .tile_C_V_12_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_we1),
    .tile_C_V_13_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_address0),
    .tile_C_V_13_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_ce0),
    .tile_C_V_13_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_d0),
    .tile_C_V_13_q0(tile_C_V_13_q0),
    .tile_C_V_13_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_we0),
    .tile_C_V_13_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_address1),
    .tile_C_V_13_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_ce1),
    .tile_C_V_13_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_d1),
    .tile_C_V_13_q1(32'd0),
    .tile_C_V_13_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_we1),
    .tile_C_V_14_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_address0),
    .tile_C_V_14_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_ce0),
    .tile_C_V_14_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_d0),
    .tile_C_V_14_q0(tile_C_V_14_q0),
    .tile_C_V_14_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_we0),
    .tile_C_V_14_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_address1),
    .tile_C_V_14_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_ce1),
    .tile_C_V_14_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_d1),
    .tile_C_V_14_q1(32'd0),
    .tile_C_V_14_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_we1),
    .tile_C_V_15_address0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_address0),
    .tile_C_V_15_ce0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_ce0),
    .tile_C_V_15_d0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_d0),
    .tile_C_V_15_q0(tile_C_V_15_q0),
    .tile_C_V_15_we0(dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_we0),
    .tile_C_V_15_address1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_address1),
    .tile_C_V_15_ce1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_ce1),
    .tile_C_V_15_d1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_d1),
    .tile_C_V_15_q1(32'd0),
    .tile_C_V_15_we1(dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_we1),
    .mat_A_ap_vld(mat_A_ap_vld),
    .k_ap_vld(1'b0),
    .i_ap_vld(i_ap_vld),
    .num_depth_tiles_ap_vld(num_depth_tiles_ap_vld),
    .ap_start(dataflow_in_loop_Depth_Loop_U0_ap_start),
    .mat_B_ap_vld(mat_B_ap_vld),
    .num_col_tiles_ap_vld(num_col_tiles_ap_vld),
    .j_ap_vld(j_ap_vld),
    .ap_done(dataflow_in_loop_Depth_Loop_U0_ap_done),
    .ap_ready(dataflow_in_loop_Depth_Loop_U0_ap_ready),
    .ap_idle(dataflow_in_loop_Depth_Loop_U0_ap_idle),
    .ap_continue(dataflow_in_loop_Depth_Loop_U0_ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_input_count <= 32'd0;
    end else begin
        if ((~(loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_Depth_Loop_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= (loop_dataflow_input_count + 32'd1);
        end else if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_Depth_Loop_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_output_count <= 32'd0;
    end else begin
        if ((~(loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_Depth_Loop_U0_ap_continue == 1'b1) & (dataflow_in_loop_Depth_Loop_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= (loop_dataflow_output_count + 32'd1);
        end else if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_Depth_Loop_U0_ap_continue == 1'b1) & (dataflow_in_loop_Depth_Loop_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= 32'd0;
        end
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_Depth_Loop_U0_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == 32'd0) & (ap_start == 1'b0) & (dataflow_in_loop_Depth_Loop_U0_ap_idle == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_Depth_Loop_U0_ap_ready == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~(loop_dataflow_output_count == bound_minus_1) | (ap_continue == 1'b1))) begin
        dataflow_in_loop_Depth_Loop_U0_ap_continue = 1'b1;
    end else begin
        dataflow_in_loop_Depth_Loop_U0_ap_continue = 1'b0;
    end
end

assign bound_minus_1 = (num_depth_tiles - 32'd1);

assign dataflow_in_loop_Depth_Loop_U0_ap_start = ap_start;

assign dataflow_in_loop_Depth_Loop_U0_k = loop_dataflow_input_count;

assign dataflow_in_loop_Depth_Loop_U0_num_depth_tiles = {{num_depth_tiles[(27 - 32'd1):0]}};

assign m_axi_gmem0_ARADDR = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARADDR;

assign m_axi_gmem0_ARBURST = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARBURST;

assign m_axi_gmem0_ARCACHE = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARCACHE;

assign m_axi_gmem0_ARID = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARID;

assign m_axi_gmem0_ARLEN = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARLEN;

assign m_axi_gmem0_ARLOCK = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARLOCK;

assign m_axi_gmem0_ARPROT = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARPROT;

assign m_axi_gmem0_ARQOS = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARQOS;

assign m_axi_gmem0_ARREGION = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARREGION;

assign m_axi_gmem0_ARSIZE = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARSIZE;

assign m_axi_gmem0_ARUSER = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARUSER;

assign m_axi_gmem0_ARVALID = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_ARVALID;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_RREADY = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem0_RREADY;

assign m_axi_gmem0_WDATA = 256'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 32'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign m_axi_gmem1_ARADDR = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARADDR;

assign m_axi_gmem1_ARBURST = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARBURST;

assign m_axi_gmem1_ARCACHE = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARCACHE;

assign m_axi_gmem1_ARID = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARID;

assign m_axi_gmem1_ARLEN = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARLEN;

assign m_axi_gmem1_ARLOCK = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARLOCK;

assign m_axi_gmem1_ARPROT = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARPROT;

assign m_axi_gmem1_ARQOS = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARQOS;

assign m_axi_gmem1_ARREGION = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARREGION;

assign m_axi_gmem1_ARSIZE = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARSIZE;

assign m_axi_gmem1_ARUSER = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARUSER;

assign m_axi_gmem1_ARVALID = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_ARVALID;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_RREADY = dataflow_in_loop_Depth_Loop_U0_m_axi_gmem1_RREADY;

assign m_axi_gmem1_WDATA = 256'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 32'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign tile_C_V_10_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_address0;

assign tile_C_V_10_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_address1;

assign tile_C_V_10_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_ce0;

assign tile_C_V_10_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_ce1;

assign tile_C_V_10_d0 = 32'd0;

assign tile_C_V_10_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_d1;

assign tile_C_V_10_we0 = 1'b0;

assign tile_C_V_10_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_10_we1;

assign tile_C_V_11_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_address0;

assign tile_C_V_11_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_address1;

assign tile_C_V_11_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_ce0;

assign tile_C_V_11_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_ce1;

assign tile_C_V_11_d0 = 32'd0;

assign tile_C_V_11_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_d1;

assign tile_C_V_11_we0 = 1'b0;

assign tile_C_V_11_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_11_we1;

assign tile_C_V_12_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_address0;

assign tile_C_V_12_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_address1;

assign tile_C_V_12_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_ce0;

assign tile_C_V_12_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_ce1;

assign tile_C_V_12_d0 = 32'd0;

assign tile_C_V_12_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_d1;

assign tile_C_V_12_we0 = 1'b0;

assign tile_C_V_12_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_12_we1;

assign tile_C_V_13_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_address0;

assign tile_C_V_13_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_address1;

assign tile_C_V_13_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_ce0;

assign tile_C_V_13_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_ce1;

assign tile_C_V_13_d0 = 32'd0;

assign tile_C_V_13_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_d1;

assign tile_C_V_13_we0 = 1'b0;

assign tile_C_V_13_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_13_we1;

assign tile_C_V_14_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_address0;

assign tile_C_V_14_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_address1;

assign tile_C_V_14_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_ce0;

assign tile_C_V_14_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_ce1;

assign tile_C_V_14_d0 = 32'd0;

assign tile_C_V_14_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_d1;

assign tile_C_V_14_we0 = 1'b0;

assign tile_C_V_14_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_14_we1;

assign tile_C_V_15_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_address0;

assign tile_C_V_15_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_address1;

assign tile_C_V_15_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_ce0;

assign tile_C_V_15_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_ce1;

assign tile_C_V_15_d0 = 32'd0;

assign tile_C_V_15_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_d1;

assign tile_C_V_15_we0 = 1'b0;

assign tile_C_V_15_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_15_we1;

assign tile_C_V_1_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_address0;

assign tile_C_V_1_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_address1;

assign tile_C_V_1_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_ce0;

assign tile_C_V_1_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_ce1;

assign tile_C_V_1_d0 = 32'd0;

assign tile_C_V_1_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_d1;

assign tile_C_V_1_we0 = 1'b0;

assign tile_C_V_1_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_1_we1;

assign tile_C_V_2_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_address0;

assign tile_C_V_2_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_address1;

assign tile_C_V_2_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_ce0;

assign tile_C_V_2_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_ce1;

assign tile_C_V_2_d0 = 32'd0;

assign tile_C_V_2_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_d1;

assign tile_C_V_2_we0 = 1'b0;

assign tile_C_V_2_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_2_we1;

assign tile_C_V_3_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_address0;

assign tile_C_V_3_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_address1;

assign tile_C_V_3_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_ce0;

assign tile_C_V_3_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_ce1;

assign tile_C_V_3_d0 = 32'd0;

assign tile_C_V_3_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_d1;

assign tile_C_V_3_we0 = 1'b0;

assign tile_C_V_3_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_3_we1;

assign tile_C_V_4_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_address0;

assign tile_C_V_4_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_address1;

assign tile_C_V_4_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_ce0;

assign tile_C_V_4_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_ce1;

assign tile_C_V_4_d0 = 32'd0;

assign tile_C_V_4_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_d1;

assign tile_C_V_4_we0 = 1'b0;

assign tile_C_V_4_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_4_we1;

assign tile_C_V_5_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_address0;

assign tile_C_V_5_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_address1;

assign tile_C_V_5_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_ce0;

assign tile_C_V_5_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_ce1;

assign tile_C_V_5_d0 = 32'd0;

assign tile_C_V_5_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_d1;

assign tile_C_V_5_we0 = 1'b0;

assign tile_C_V_5_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_5_we1;

assign tile_C_V_6_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_address0;

assign tile_C_V_6_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_address1;

assign tile_C_V_6_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_ce0;

assign tile_C_V_6_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_ce1;

assign tile_C_V_6_d0 = 32'd0;

assign tile_C_V_6_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_d1;

assign tile_C_V_6_we0 = 1'b0;

assign tile_C_V_6_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_6_we1;

assign tile_C_V_7_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_address0;

assign tile_C_V_7_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_address1;

assign tile_C_V_7_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_ce0;

assign tile_C_V_7_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_ce1;

assign tile_C_V_7_d0 = 32'd0;

assign tile_C_V_7_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_d1;

assign tile_C_V_7_we0 = 1'b0;

assign tile_C_V_7_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_7_we1;

assign tile_C_V_8_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_address0;

assign tile_C_V_8_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_address1;

assign tile_C_V_8_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_ce0;

assign tile_C_V_8_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_ce1;

assign tile_C_V_8_d0 = 32'd0;

assign tile_C_V_8_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_d1;

assign tile_C_V_8_we0 = 1'b0;

assign tile_C_V_8_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_8_we1;

assign tile_C_V_9_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_address0;

assign tile_C_V_9_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_address1;

assign tile_C_V_9_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_ce0;

assign tile_C_V_9_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_ce1;

assign tile_C_V_9_d0 = 32'd0;

assign tile_C_V_9_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_d1;

assign tile_C_V_9_we0 = 1'b0;

assign tile_C_V_9_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_9_we1;

assign tile_C_V_address0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_address0;

assign tile_C_V_address1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_address1;

assign tile_C_V_ce0 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_ce0;

assign tile_C_V_ce1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_ce1;

assign tile_C_V_d0 = 32'd0;

assign tile_C_V_d1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_d1;

assign tile_C_V_we0 = 1'b0;

assign tile_C_V_we1 = dataflow_in_loop_Depth_Loop_U0_tile_C_V_we1;

endmodule //pipelined_layer_processor_dataflow_parent_loop_proc
