// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pipelined_layer_processor_pipelined_layer_processor_Pipeline_Clear (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tile_C_V_address1,
        tile_C_V_ce1,
        tile_C_V_we1,
        tile_C_V_d1,
        tile_C_V_1_address1,
        tile_C_V_1_ce1,
        tile_C_V_1_we1,
        tile_C_V_1_d1,
        tile_C_V_2_address1,
        tile_C_V_2_ce1,
        tile_C_V_2_we1,
        tile_C_V_2_d1,
        tile_C_V_3_address1,
        tile_C_V_3_ce1,
        tile_C_V_3_we1,
        tile_C_V_3_d1,
        tile_C_V_4_address1,
        tile_C_V_4_ce1,
        tile_C_V_4_we1,
        tile_C_V_4_d1,
        tile_C_V_5_address1,
        tile_C_V_5_ce1,
        tile_C_V_5_we1,
        tile_C_V_5_d1,
        tile_C_V_6_address1,
        tile_C_V_6_ce1,
        tile_C_V_6_we1,
        tile_C_V_6_d1,
        tile_C_V_7_address1,
        tile_C_V_7_ce1,
        tile_C_V_7_we1,
        tile_C_V_7_d1,
        tile_C_V_8_address1,
        tile_C_V_8_ce1,
        tile_C_V_8_we1,
        tile_C_V_8_d1,
        tile_C_V_9_address1,
        tile_C_V_9_ce1,
        tile_C_V_9_we1,
        tile_C_V_9_d1,
        tile_C_V_10_address1,
        tile_C_V_10_ce1,
        tile_C_V_10_we1,
        tile_C_V_10_d1,
        tile_C_V_11_address1,
        tile_C_V_11_ce1,
        tile_C_V_11_we1,
        tile_C_V_11_d1,
        tile_C_V_12_address1,
        tile_C_V_12_ce1,
        tile_C_V_12_we1,
        tile_C_V_12_d1,
        tile_C_V_13_address1,
        tile_C_V_13_ce1,
        tile_C_V_13_we1,
        tile_C_V_13_d1,
        tile_C_V_14_address1,
        tile_C_V_14_ce1,
        tile_C_V_14_we1,
        tile_C_V_14_d1,
        tile_C_V_15_address1,
        tile_C_V_15_ce1,
        tile_C_V_15_we1,
        tile_C_V_15_d1
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] tile_C_V_address1;
output   tile_C_V_ce1;
output   tile_C_V_we1;
output  [31:0] tile_C_V_d1;
output  [5:0] tile_C_V_1_address1;
output   tile_C_V_1_ce1;
output   tile_C_V_1_we1;
output  [31:0] tile_C_V_1_d1;
output  [5:0] tile_C_V_2_address1;
output   tile_C_V_2_ce1;
output   tile_C_V_2_we1;
output  [31:0] tile_C_V_2_d1;
output  [5:0] tile_C_V_3_address1;
output   tile_C_V_3_ce1;
output   tile_C_V_3_we1;
output  [31:0] tile_C_V_3_d1;
output  [5:0] tile_C_V_4_address1;
output   tile_C_V_4_ce1;
output   tile_C_V_4_we1;
output  [31:0] tile_C_V_4_d1;
output  [5:0] tile_C_V_5_address1;
output   tile_C_V_5_ce1;
output   tile_C_V_5_we1;
output  [31:0] tile_C_V_5_d1;
output  [5:0] tile_C_V_6_address1;
output   tile_C_V_6_ce1;
output   tile_C_V_6_we1;
output  [31:0] tile_C_V_6_d1;
output  [5:0] tile_C_V_7_address1;
output   tile_C_V_7_ce1;
output   tile_C_V_7_we1;
output  [31:0] tile_C_V_7_d1;
output  [5:0] tile_C_V_8_address1;
output   tile_C_V_8_ce1;
output   tile_C_V_8_we1;
output  [31:0] tile_C_V_8_d1;
output  [5:0] tile_C_V_9_address1;
output   tile_C_V_9_ce1;
output   tile_C_V_9_we1;
output  [31:0] tile_C_V_9_d1;
output  [5:0] tile_C_V_10_address1;
output   tile_C_V_10_ce1;
output   tile_C_V_10_we1;
output  [31:0] tile_C_V_10_d1;
output  [5:0] tile_C_V_11_address1;
output   tile_C_V_11_ce1;
output   tile_C_V_11_we1;
output  [31:0] tile_C_V_11_d1;
output  [5:0] tile_C_V_12_address1;
output   tile_C_V_12_ce1;
output   tile_C_V_12_we1;
output  [31:0] tile_C_V_12_d1;
output  [5:0] tile_C_V_13_address1;
output   tile_C_V_13_ce1;
output   tile_C_V_13_we1;
output  [31:0] tile_C_V_13_d1;
output  [5:0] tile_C_V_14_address1;
output   tile_C_V_14_ce1;
output   tile_C_V_14_we1;
output  [31:0] tile_C_V_14_d1;
output  [5:0] tile_C_V_15_address1;
output   tile_C_V_15_ce1;
output   tile_C_V_15_we1;
output  [31:0] tile_C_V_15_d1;

reg ap_idle;
reg[5:0] tile_C_V_address1;
reg tile_C_V_ce1;
reg tile_C_V_we1;
reg[5:0] tile_C_V_1_address1;
reg tile_C_V_1_ce1;
reg tile_C_V_1_we1;
reg[5:0] tile_C_V_2_address1;
reg tile_C_V_2_ce1;
reg tile_C_V_2_we1;
reg[5:0] tile_C_V_3_address1;
reg tile_C_V_3_ce1;
reg tile_C_V_3_we1;
reg[5:0] tile_C_V_4_address1;
reg tile_C_V_4_ce1;
reg tile_C_V_4_we1;
reg[5:0] tile_C_V_5_address1;
reg tile_C_V_5_ce1;
reg tile_C_V_5_we1;
reg[5:0] tile_C_V_6_address1;
reg tile_C_V_6_ce1;
reg tile_C_V_6_we1;
reg[5:0] tile_C_V_7_address1;
reg tile_C_V_7_ce1;
reg tile_C_V_7_we1;
reg[5:0] tile_C_V_8_address1;
reg tile_C_V_8_ce1;
reg tile_C_V_8_we1;
reg[5:0] tile_C_V_9_address1;
reg tile_C_V_9_ce1;
reg tile_C_V_9_we1;
reg[5:0] tile_C_V_10_address1;
reg tile_C_V_10_ce1;
reg tile_C_V_10_we1;
reg[5:0] tile_C_V_11_address1;
reg tile_C_V_11_ce1;
reg tile_C_V_11_we1;
reg[5:0] tile_C_V_12_address1;
reg tile_C_V_12_ce1;
reg tile_C_V_12_we1;
reg[5:0] tile_C_V_13_address1;
reg tile_C_V_13_ce1;
reg tile_C_V_13_we1;
reg[5:0] tile_C_V_14_address1;
reg tile_C_V_14_ce1;
reg tile_C_V_14_we1;
reg[5:0] tile_C_V_15_address1;
reg tile_C_V_15_ce1;
reg tile_C_V_15_we1;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln171_fu_492_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state2;
wire    ap_block_state2_pp0_stage1_iter0;
wire   [5:0] shl_ln173_fu_504_p2;
reg   [5:0] shl_ln173_reg_570;
wire   [63:0] zext_ln173_fu_510_p1;
wire   [63:0] zext_ln173_1_fu_540_p1;
reg   [5:0] r_fu_64;
wire   [5:0] add_ln171_fu_498_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_r_1;
wire   [5:0] or_ln173_fu_535_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

pipelined_layer_processor_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln171_fu_492_p2 == 1'd0)) begin
            r_fu_64 <= add_ln171_fu_498_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_64 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        shl_ln173_reg_570[5 : 1] <= shl_ln173_fu_504_p2[5 : 1];
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln171_fu_492_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_r_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_r_1 = r_fu_64;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_10_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_10_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_10_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_10_ce1 = 1'b1;
    end else begin
        tile_C_V_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_10_we1 = 1'b1;
    end else begin
        tile_C_V_10_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_11_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_11_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_11_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_11_ce1 = 1'b1;
    end else begin
        tile_C_V_11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_11_we1 = 1'b1;
    end else begin
        tile_C_V_11_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_12_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_12_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_12_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_12_ce1 = 1'b1;
    end else begin
        tile_C_V_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_12_we1 = 1'b1;
    end else begin
        tile_C_V_12_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_13_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_13_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_13_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_13_ce1 = 1'b1;
    end else begin
        tile_C_V_13_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_13_we1 = 1'b1;
    end else begin
        tile_C_V_13_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_14_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_14_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_14_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_14_ce1 = 1'b1;
    end else begin
        tile_C_V_14_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_14_we1 = 1'b1;
    end else begin
        tile_C_V_14_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_15_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_15_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_15_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_15_ce1 = 1'b1;
    end else begin
        tile_C_V_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_15_we1 = 1'b1;
    end else begin
        tile_C_V_15_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_1_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_1_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_1_ce1 = 1'b1;
    end else begin
        tile_C_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_1_we1 = 1'b1;
    end else begin
        tile_C_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_2_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_2_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_2_ce1 = 1'b1;
    end else begin
        tile_C_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_2_we1 = 1'b1;
    end else begin
        tile_C_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_3_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_3_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_3_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_3_ce1 = 1'b1;
    end else begin
        tile_C_V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_3_we1 = 1'b1;
    end else begin
        tile_C_V_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_4_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_4_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_4_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_4_ce1 = 1'b1;
    end else begin
        tile_C_V_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_4_we1 = 1'b1;
    end else begin
        tile_C_V_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_5_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_5_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_5_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_5_ce1 = 1'b1;
    end else begin
        tile_C_V_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_5_we1 = 1'b1;
    end else begin
        tile_C_V_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_6_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_6_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_6_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_6_ce1 = 1'b1;
    end else begin
        tile_C_V_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_6_we1 = 1'b1;
    end else begin
        tile_C_V_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_7_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_7_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_7_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_7_ce1 = 1'b1;
    end else begin
        tile_C_V_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_7_we1 = 1'b1;
    end else begin
        tile_C_V_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_8_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_8_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_8_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_8_ce1 = 1'b1;
    end else begin
        tile_C_V_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_8_we1 = 1'b1;
    end else begin
        tile_C_V_8_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_9_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_9_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_9_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_9_ce1 = 1'b1;
    end else begin
        tile_C_V_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_9_we1 = 1'b1;
    end else begin
        tile_C_V_9_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tile_C_V_address1 = zext_ln173_1_fu_540_p1;
    end else if (((icmp_ln171_fu_492_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_C_V_address1 = zext_ln173_fu_510_p1;
    end else begin
        tile_C_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_ce1 = 1'b1;
    end else begin
        tile_C_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((icmp_ln171_fu_492_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        tile_C_V_we1 = 1'b1;
    end else begin
        tile_C_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln171_fu_492_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln171_fu_498_p2 = (ap_sig_allocacmp_r_1 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln171_fu_492_p2 = ((ap_sig_allocacmp_r_1 == 6'd32) ? 1'b1 : 1'b0);

assign or_ln173_fu_535_p2 = (shl_ln173_reg_570 | 6'd1);

assign shl_ln173_fu_504_p2 = ap_sig_allocacmp_r_1 << 6'd1;

assign tile_C_V_10_d1 = 32'd0;

assign tile_C_V_11_d1 = 32'd0;

assign tile_C_V_12_d1 = 32'd0;

assign tile_C_V_13_d1 = 32'd0;

assign tile_C_V_14_d1 = 32'd0;

assign tile_C_V_15_d1 = 32'd0;

assign tile_C_V_1_d1 = 32'd0;

assign tile_C_V_2_d1 = 32'd0;

assign tile_C_V_3_d1 = 32'd0;

assign tile_C_V_4_d1 = 32'd0;

assign tile_C_V_5_d1 = 32'd0;

assign tile_C_V_6_d1 = 32'd0;

assign tile_C_V_7_d1 = 32'd0;

assign tile_C_V_8_d1 = 32'd0;

assign tile_C_V_9_d1 = 32'd0;

assign tile_C_V_d1 = 32'd0;

assign zext_ln173_1_fu_540_p1 = or_ln173_fu_535_p2;

assign zext_ln173_fu_510_p1 = shl_ln173_fu_504_p2;

always @ (posedge ap_clk) begin
    shl_ln173_reg_570[0] <= 1'b0;
end

endmodule //pipelined_layer_processor_pipelined_layer_processor_Pipeline_Clear
