-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pipelined_layer_processor_write_big_tile_Pipeline_Write_Rows_Write_Cols is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln111_1 : IN STD_LOGIC_VECTOR (58 downto 0);
    local_buffer_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_0_ce0 : OUT STD_LOGIC;
    local_buffer_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_1_ce0 : OUT STD_LOGIC;
    local_buffer_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_2_ce0 : OUT STD_LOGIC;
    local_buffer_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_3_ce0 : OUT STD_LOGIC;
    local_buffer_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_4_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_4_ce0 : OUT STD_LOGIC;
    local_buffer_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_5_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_5_ce0 : OUT STD_LOGIC;
    local_buffer_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_6_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_6_ce0 : OUT STD_LOGIC;
    local_buffer_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_7_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_7_ce0 : OUT STD_LOGIC;
    local_buffer_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_8_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_8_ce0 : OUT STD_LOGIC;
    local_buffer_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_9_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_9_ce0 : OUT STD_LOGIC;
    local_buffer_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_10_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_10_ce0 : OUT STD_LOGIC;
    local_buffer_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_11_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_11_ce0 : OUT STD_LOGIC;
    local_buffer_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_12_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_12_ce0 : OUT STD_LOGIC;
    local_buffer_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_13_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_13_ce0 : OUT STD_LOGIC;
    local_buffer_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_14_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_14_ce0 : OUT STD_LOGIC;
    local_buffer_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_15_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_15_ce0 : OUT STD_LOGIC;
    local_buffer_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of pipelined_layer_processor_write_big_tile_Pipeline_Write_Rows_Write_Cols is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv6_8 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln111_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln111_reg_621 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln186_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln186_reg_705 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln186_fu_519_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_reg_722 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_1_fu_526_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_1_reg_727 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_2_fu_533_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_2_reg_732 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_3_fu_540_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_3_reg_737 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_4_fu_547_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_4_reg_742 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_5_fu_554_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_5_reg_747 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_6_fu_561_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_6_reg_752 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_7_fu_568_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln186_7_reg_757 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal zext_ln186_fu_444_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal c_fu_110 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln112_fu_474_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_fu_114 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln112_fu_486_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_indvar_load : STD_LOGIC_VECTOR (2 downto 0);
    signal r_fu_118 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln111_1_fu_416_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_r_load : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten_fu_122 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln111_fu_381_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln112_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln111_1_fu_396_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln111_fu_408_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln113_fu_424_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_1_fu_428_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_436_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln186_fu_464_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln112_1_fu_480_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pipelined_layer_processor_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component pipelined_layer_processor_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    c_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln111_fu_375_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_110 <= add_ln112_fu_474_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_110 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln111_fu_375_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_122 <= add_ln111_fu_381_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_122 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln111_fu_375_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_fu_114 <= select_ln112_fu_486_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_fu_114 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    r_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln111_fu_375_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    r_fu_118 <= select_ln111_1_fu_416_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    r_fu_118 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln111_reg_621 <= icmp_ln111_fu_375_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln111_fu_375_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln186_reg_705 <= icmp_ln186_fu_468_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln111_reg_621 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln186_1_reg_727 <= select_ln186_1_fu_526_p3;
                select_ln186_2_reg_732 <= select_ln186_2_fu_533_p3;
                select_ln186_3_reg_737 <= select_ln186_3_fu_540_p3;
                select_ln186_4_reg_742 <= select_ln186_4_fu_547_p3;
                select_ln186_5_reg_747 <= select_ln186_5_fu_554_p3;
                select_ln186_6_reg_752 <= select_ln186_6_fu_561_p3;
                select_ln186_7_reg_757 <= select_ln186_7_fu_568_p3;
                select_ln186_reg_722 <= select_ln186_fu_519_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln111_1_fu_396_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_r_load) + unsigned(ap_const_lv6_1));
    add_ln111_fu_381_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv8_1));
    add_ln112_1_fu_480_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_load) + unsigned(ap_const_lv3_1));
    add_ln112_fu_474_p2 <= std_logic_vector(unsigned(select_ln111_fu_408_p3) + unsigned(ap_const_lv6_8));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem0_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem0_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln111_fu_375_p2)
    begin
        if (((icmp_ln111_fu_375_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln111_reg_621)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln111_reg_621 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, c_fu_110, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_110;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_122)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_122;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_fu_114)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_indvar_load <= indvar_fu_114;
        end if; 
    end process;


    ap_sig_allocacmp_r_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, r_fu_118)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_r_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_r_load <= r_fu_118;
        end if; 
    end process;


    gmem0_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem0_WREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            gmem0_blk_n_W <= m_axi_gmem0_WREADY;
        else 
            gmem0_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln111_fu_375_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv8_80) else "0";
    icmp_ln112_fu_402_p2 <= "1" when (ap_sig_allocacmp_indvar_load = ap_const_lv3_4) else "0";
    icmp_ln186_fu_468_p2 <= "1" when (trunc_ln186_fu_464_p1 = ap_const_lv4_8) else "0";
    local_buffer_0_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_0_ce0 <= ap_const_logic_1;
        else 
            local_buffer_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_10_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_10_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_10_ce0 <= ap_const_logic_1;
        else 
            local_buffer_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_11_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_11_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_11_ce0 <= ap_const_logic_1;
        else 
            local_buffer_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_12_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_12_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_12_ce0 <= ap_const_logic_1;
        else 
            local_buffer_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_13_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_13_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_13_ce0 <= ap_const_logic_1;
        else 
            local_buffer_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_14_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_14_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_14_ce0 <= ap_const_logic_1;
        else 
            local_buffer_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_15_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_15_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_15_ce0 <= ap_const_logic_1;
        else 
            local_buffer_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_1_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_1_ce0 <= ap_const_logic_1;
        else 
            local_buffer_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_2_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_2_ce0 <= ap_const_logic_1;
        else 
            local_buffer_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_3_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_3_ce0 <= ap_const_logic_1;
        else 
            local_buffer_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_4_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_4_ce0 <= ap_const_logic_1;
        else 
            local_buffer_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_5_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_5_ce0 <= ap_const_logic_1;
        else 
            local_buffer_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_6_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_6_ce0 <= ap_const_logic_1;
        else 
            local_buffer_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_7_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_7_ce0 <= ap_const_logic_1;
        else 
            local_buffer_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_8_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_8_ce0 <= ap_const_logic_1;
        else 
            local_buffer_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_9_address0 <= zext_ln186_fu_444_p1(6 - 1 downto 0);

    local_buffer_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_buffer_9_ce0 <= ap_const_logic_1;
        else 
            local_buffer_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;
    m_axi_gmem0_RREADY <= ap_const_logic_0;
    m_axi_gmem0_WDATA <= (((((((select_ln186_7_reg_757 & select_ln186_6_reg_752) & select_ln186_5_reg_747) & select_ln186_4_reg_742) & select_ln186_3_reg_737) & select_ln186_2_reg_732) & select_ln186_1_reg_727) & select_ln186_reg_722);
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv32_FFFFFFFF;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;

    m_axi_gmem0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            m_axi_gmem0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    select_ln111_1_fu_416_p3 <= 
        add_ln111_1_fu_396_p2 when (icmp_ln112_fu_402_p2(0) = '1') else 
        ap_sig_allocacmp_r_load;
    select_ln111_fu_408_p3 <= 
        ap_const_lv6_0 when (icmp_ln112_fu_402_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
    select_ln112_fu_486_p3 <= 
        ap_const_lv3_1 when (icmp_ln112_fu_402_p2(0) = '1') else 
        add_ln112_1_fu_480_p2;
    select_ln186_1_fu_526_p3 <= 
        local_buffer_9_q0 when (icmp_ln186_reg_705(0) = '1') else 
        local_buffer_1_q0;
    select_ln186_2_fu_533_p3 <= 
        local_buffer_10_q0 when (icmp_ln186_reg_705(0) = '1') else 
        local_buffer_2_q0;
    select_ln186_3_fu_540_p3 <= 
        local_buffer_11_q0 when (icmp_ln186_reg_705(0) = '1') else 
        local_buffer_3_q0;
    select_ln186_4_fu_547_p3 <= 
        local_buffer_12_q0 when (icmp_ln186_reg_705(0) = '1') else 
        local_buffer_4_q0;
    select_ln186_5_fu_554_p3 <= 
        local_buffer_13_q0 when (icmp_ln186_reg_705(0) = '1') else 
        local_buffer_5_q0;
    select_ln186_6_fu_561_p3 <= 
        local_buffer_14_q0 when (icmp_ln186_reg_705(0) = '1') else 
        local_buffer_6_q0;
    select_ln186_7_fu_568_p3 <= 
        local_buffer_15_q0 when (icmp_ln186_reg_705(0) = '1') else 
        local_buffer_7_q0;
    select_ln186_fu_519_p3 <= 
        local_buffer_8_q0 when (icmp_ln186_reg_705(0) = '1') else 
        local_buffer_0_q0;
    tmp_1_fu_428_p3 <= select_ln111_fu_408_p3(4 downto 4);
    tmp_fu_436_p3 <= (trunc_ln113_fu_424_p1 & tmp_1_fu_428_p3);
    trunc_ln113_fu_424_p1 <= select_ln111_1_fu_416_p3(5 - 1 downto 0);
    trunc_ln186_fu_464_p1 <= select_ln111_fu_408_p3(4 - 1 downto 0);
    zext_ln186_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_436_p3),64));
end behav;
