-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pipelined_layer_processor_read_big_tile_Pipeline_Read_Loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln15_2 : IN STD_LOGIC_VECTOR (58 downto 0);
    local_buffer_0_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_0_ce1 : OUT STD_LOGIC;
    local_buffer_0_we1 : OUT STD_LOGIC;
    local_buffer_0_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_1_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_1_ce1 : OUT STD_LOGIC;
    local_buffer_1_we1 : OUT STD_LOGIC;
    local_buffer_1_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_2_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_2_ce1 : OUT STD_LOGIC;
    local_buffer_2_we1 : OUT STD_LOGIC;
    local_buffer_2_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_3_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_3_ce1 : OUT STD_LOGIC;
    local_buffer_3_we1 : OUT STD_LOGIC;
    local_buffer_3_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_4_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_4_ce1 : OUT STD_LOGIC;
    local_buffer_4_we1 : OUT STD_LOGIC;
    local_buffer_4_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_5_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_5_ce1 : OUT STD_LOGIC;
    local_buffer_5_we1 : OUT STD_LOGIC;
    local_buffer_5_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_6_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_6_ce1 : OUT STD_LOGIC;
    local_buffer_6_we1 : OUT STD_LOGIC;
    local_buffer_6_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_7_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_7_ce1 : OUT STD_LOGIC;
    local_buffer_7_we1 : OUT STD_LOGIC;
    local_buffer_7_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_8_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_8_ce1 : OUT STD_LOGIC;
    local_buffer_8_we1 : OUT STD_LOGIC;
    local_buffer_8_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_9_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_9_ce1 : OUT STD_LOGIC;
    local_buffer_9_we1 : OUT STD_LOGIC;
    local_buffer_9_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_10_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_10_ce1 : OUT STD_LOGIC;
    local_buffer_10_we1 : OUT STD_LOGIC;
    local_buffer_10_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_11_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_11_ce1 : OUT STD_LOGIC;
    local_buffer_11_we1 : OUT STD_LOGIC;
    local_buffer_11_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_12_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_12_ce1 : OUT STD_LOGIC;
    local_buffer_12_we1 : OUT STD_LOGIC;
    local_buffer_12_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_13_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_13_ce1 : OUT STD_LOGIC;
    local_buffer_13_we1 : OUT STD_LOGIC;
    local_buffer_13_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_14_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_14_ce1 : OUT STD_LOGIC;
    local_buffer_14_we1 : OUT STD_LOGIC;
    local_buffer_14_d1 : OUT STD_LOGIC_VECTOR (255 downto 0);
    local_buffer_15_address1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    local_buffer_15_ce1 : OUT STD_LOGIC;
    local_buffer_15_we1 : OUT STD_LOGIC;
    local_buffer_15_d1 : OUT STD_LOGIC_VECTOR (255 downto 0) );
end;


architecture behav of pipelined_layer_processor_read_big_tile_Pipeline_Read_Loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv256_lc_1 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln15_reg_485 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln15_fu_419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_reg_489 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_489_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln22_fu_439_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln22_reg_494 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln22_reg_494_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Val2_s_reg_498 : STD_LOGIC_VECTOR (255 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal zext_ln22_fu_454_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_120 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln15_fu_425_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pipelined_layer_processor_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component pipelined_layer_processor_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln15_fu_419_p2 = ap_const_lv1_0))) then 
                    i_fu_120 <= add_ln15_fu_425_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_120 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln15_reg_485 <= icmp_ln15_fu_419_p2;
                tmp_reg_489_pp0_iter1_reg <= tmp_reg_489;
                trunc_ln22_reg_494_pp0_iter1_reg <= trunc_ln22_reg_494;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln15_reg_485 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                p_Val2_s_reg_498 <= m_axi_gmem0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln15_fu_419_p2 = ap_const_lv1_0))) then
                tmp_reg_489 <= ap_sig_allocacmp_i_1(4 downto 4);
                trunc_ln22_reg_494 <= trunc_ln22_fu_439_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln15_fu_425_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem0_RVALID, icmp_ln15_reg_485)
    begin
                ap_block_pp0_stage0_11001 <= ((icmp_ln15_reg_485 = ap_const_lv1_0) and (m_axi_gmem0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem0_RVALID, icmp_ln15_reg_485)
    begin
                ap_block_pp0_stage0_subdone <= ((icmp_ln15_reg_485 = ap_const_lv1_0) and (m_axi_gmem0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_gmem0_RVALID, icmp_ln15_reg_485)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln15_reg_485 = ap_const_lv1_0) and (m_axi_gmem0_RVALID = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln15_fu_419_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln15_fu_419_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln15_reg_485, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln15_reg_485 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_120, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_120;
        end if; 
    end process;


    gmem0_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem0_RVALID, icmp_ln15_reg_485, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln15_reg_485 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem0_blk_n_R <= m_axi_gmem0_RVALID;
        else 
            gmem0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln15_fu_419_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv6_20) else "0";
    local_buffer_0_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_0_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_0_ce1 <= ap_const_logic_1;
        else 
            local_buffer_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_0_d1 <= p_Val2_s_reg_498;

    local_buffer_0_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_0))) then 
            local_buffer_0_we1 <= ap_const_logic_1;
        else 
            local_buffer_0_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_10_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_10_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_10_ce1 <= ap_const_logic_1;
        else 
            local_buffer_10_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_10_d1 <= p_Val2_s_reg_498;

    local_buffer_10_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_A))) then 
            local_buffer_10_we1 <= ap_const_logic_1;
        else 
            local_buffer_10_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_11_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_11_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_11_ce1 <= ap_const_logic_1;
        else 
            local_buffer_11_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_11_d1 <= p_Val2_s_reg_498;

    local_buffer_11_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_B))) then 
            local_buffer_11_we1 <= ap_const_logic_1;
        else 
            local_buffer_11_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_12_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_12_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_12_ce1 <= ap_const_logic_1;
        else 
            local_buffer_12_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_12_d1 <= p_Val2_s_reg_498;

    local_buffer_12_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_C))) then 
            local_buffer_12_we1 <= ap_const_logic_1;
        else 
            local_buffer_12_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_13_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_13_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_13_ce1 <= ap_const_logic_1;
        else 
            local_buffer_13_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_13_d1 <= p_Val2_s_reg_498;

    local_buffer_13_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_D))) then 
            local_buffer_13_we1 <= ap_const_logic_1;
        else 
            local_buffer_13_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_14_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_14_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_14_ce1 <= ap_const_logic_1;
        else 
            local_buffer_14_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_14_d1 <= p_Val2_s_reg_498;

    local_buffer_14_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_E))) then 
            local_buffer_14_we1 <= ap_const_logic_1;
        else 
            local_buffer_14_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_15_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_15_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_15_ce1 <= ap_const_logic_1;
        else 
            local_buffer_15_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_15_d1 <= p_Val2_s_reg_498;

    local_buffer_15_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_F))) then 
            local_buffer_15_we1 <= ap_const_logic_1;
        else 
            local_buffer_15_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_1_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_1_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_1_ce1 <= ap_const_logic_1;
        else 
            local_buffer_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_1_d1 <= p_Val2_s_reg_498;

    local_buffer_1_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_1))) then 
            local_buffer_1_we1 <= ap_const_logic_1;
        else 
            local_buffer_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_2_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_2_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_2_ce1 <= ap_const_logic_1;
        else 
            local_buffer_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_2_d1 <= p_Val2_s_reg_498;

    local_buffer_2_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_2))) then 
            local_buffer_2_we1 <= ap_const_logic_1;
        else 
            local_buffer_2_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_3_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_3_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_3_ce1 <= ap_const_logic_1;
        else 
            local_buffer_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_3_d1 <= p_Val2_s_reg_498;

    local_buffer_3_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_3))) then 
            local_buffer_3_we1 <= ap_const_logic_1;
        else 
            local_buffer_3_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_4_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_4_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_4_ce1 <= ap_const_logic_1;
        else 
            local_buffer_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_4_d1 <= p_Val2_s_reg_498;

    local_buffer_4_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_4))) then 
            local_buffer_4_we1 <= ap_const_logic_1;
        else 
            local_buffer_4_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_5_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_5_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_5_ce1 <= ap_const_logic_1;
        else 
            local_buffer_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_5_d1 <= p_Val2_s_reg_498;

    local_buffer_5_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_5))) then 
            local_buffer_5_we1 <= ap_const_logic_1;
        else 
            local_buffer_5_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_6_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_6_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_6_ce1 <= ap_const_logic_1;
        else 
            local_buffer_6_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_6_d1 <= p_Val2_s_reg_498;

    local_buffer_6_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_6))) then 
            local_buffer_6_we1 <= ap_const_logic_1;
        else 
            local_buffer_6_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_7_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_7_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_7_ce1 <= ap_const_logic_1;
        else 
            local_buffer_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_7_d1 <= p_Val2_s_reg_498;

    local_buffer_7_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_7))) then 
            local_buffer_7_we1 <= ap_const_logic_1;
        else 
            local_buffer_7_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_8_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_8_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_8_ce1 <= ap_const_logic_1;
        else 
            local_buffer_8_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_8_d1 <= p_Val2_s_reg_498;

    local_buffer_8_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_8))) then 
            local_buffer_8_we1 <= ap_const_logic_1;
        else 
            local_buffer_8_we1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_9_address1 <= zext_ln22_fu_454_p1(1 - 1 downto 0);

    local_buffer_9_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_buffer_9_ce1 <= ap_const_logic_1;
        else 
            local_buffer_9_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    local_buffer_9_d1 <= p_Val2_s_reg_498;

    local_buffer_9_we1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln22_reg_494_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln22_reg_494_pp0_iter1_reg = ap_const_lv4_9))) then 
            local_buffer_9_we1 <= ap_const_logic_1;
        else 
            local_buffer_9_we1 <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln15_reg_485, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln15_reg_485 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv256_lc_1;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv32_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    trunc_ln22_fu_439_p1 <= ap_sig_allocacmp_i_1(4 - 1 downto 0);
    zext_ln22_fu_454_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_489_pp0_iter1_reg),64));
end behav;
