-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pipelined_layer_processor_write_big_tile is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    local_buffer_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_0_ce0 : OUT STD_LOGIC;
    local_buffer_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_1_ce0 : OUT STD_LOGIC;
    local_buffer_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_2_ce0 : OUT STD_LOGIC;
    local_buffer_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_3_ce0 : OUT STD_LOGIC;
    local_buffer_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_4_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_4_ce0 : OUT STD_LOGIC;
    local_buffer_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_5_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_5_ce0 : OUT STD_LOGIC;
    local_buffer_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_6_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_6_ce0 : OUT STD_LOGIC;
    local_buffer_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_7_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_7_ce0 : OUT STD_LOGIC;
    local_buffer_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_8_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_8_ce0 : OUT STD_LOGIC;
    local_buffer_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_9_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_9_ce0 : OUT STD_LOGIC;
    local_buffer_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_10_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_10_ce0 : OUT STD_LOGIC;
    local_buffer_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_11_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_11_ce0 : OUT STD_LOGIC;
    local_buffer_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_12_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_12_ce0 : OUT STD_LOGIC;
    local_buffer_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_13_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_13_ce0 : OUT STD_LOGIC;
    local_buffer_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_14_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_14_ce0 : OUT STD_LOGIC;
    local_buffer_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    local_buffer_15_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    local_buffer_15_ce0 : OUT STD_LOGIC;
    local_buffer_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    dram_matrix : IN STD_LOGIC_VECTOR (63 downto 0);
    tile_index : IN STD_LOGIC_VECTOR (24 downto 0) );
end;


architecture behav of pipelined_layer_processor_write_big_tile is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv256_lc_1 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal gmem0_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal gmem0_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal trunc_ln_reg_185 : STD_LOGIC_VECTOR (58 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_done : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_idle : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_ready : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWVALID : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WVALID : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WDATA : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WSTRB : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WLAST : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARVALID : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_RREADY : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_BREADY : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_0_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_0_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_1_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_1_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_2_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_2_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_3_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_3_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_4_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_4_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_5_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_5_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_6_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_6_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_7_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_7_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_8_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_8_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_9_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_9_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_10_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_10_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_11_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_11_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_12_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_12_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_13_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_13_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_14_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_14_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_15_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_15_ce0 : STD_LOGIC;
    signal grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal sext_ln111_1_fu_175_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln_fu_147_p3 : STD_LOGIC_VECTOR (36 downto 0);
    signal sext_ln111_fu_155_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln111_fu_159_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component pipelined_layer_processor_write_big_tile_Pipeline_Write_Rows_Write_Cols IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (255 downto 0);
        m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (255 downto 0);
        m_axi_gmem0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        sext_ln111_1 : IN STD_LOGIC_VECTOR (58 downto 0);
        local_buffer_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_0_ce0 : OUT STD_LOGIC;
        local_buffer_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_1_ce0 : OUT STD_LOGIC;
        local_buffer_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_2_ce0 : OUT STD_LOGIC;
        local_buffer_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_3_ce0 : OUT STD_LOGIC;
        local_buffer_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_4_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_4_ce0 : OUT STD_LOGIC;
        local_buffer_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_5_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_5_ce0 : OUT STD_LOGIC;
        local_buffer_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_6_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_6_ce0 : OUT STD_LOGIC;
        local_buffer_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_7_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_7_ce0 : OUT STD_LOGIC;
        local_buffer_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_8_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_8_ce0 : OUT STD_LOGIC;
        local_buffer_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_9_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_9_ce0 : OUT STD_LOGIC;
        local_buffer_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_10_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_10_ce0 : OUT STD_LOGIC;
        local_buffer_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_11_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_11_ce0 : OUT STD_LOGIC;
        local_buffer_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_12_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_12_ce0 : OUT STD_LOGIC;
        local_buffer_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_13_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_13_ce0 : OUT STD_LOGIC;
        local_buffer_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_14_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_14_ce0 : OUT STD_LOGIC;
        local_buffer_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_buffer_15_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        local_buffer_15_ce0 : OUT STD_LOGIC;
        local_buffer_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108 : component pipelined_layer_processor_write_big_tile_Pipeline_Write_Rows_Write_Cols
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start,
        ap_done => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_done,
        ap_idle => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_idle,
        ap_ready => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_ready,
        m_axi_gmem0_AWVALID => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY => m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY => m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WLAST,
        m_axi_gmem0_WID => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WID,
        m_axi_gmem0_WUSER => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY => ap_const_logic_0,
        m_axi_gmem0_ARADDR => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID => ap_const_logic_0,
        m_axi_gmem0_RREADY => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA => ap_const_lv256_lc_1,
        m_axi_gmem0_RLAST => ap_const_logic_0,
        m_axi_gmem0_RID => ap_const_lv1_0,
        m_axi_gmem0_RFIFONUM => ap_const_lv9_0,
        m_axi_gmem0_RUSER => ap_const_lv1_0,
        m_axi_gmem0_RRESP => ap_const_lv2_0,
        m_axi_gmem0_BVALID => m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP => m_axi_gmem0_BRESP,
        m_axi_gmem0_BID => m_axi_gmem0_BID,
        m_axi_gmem0_BUSER => m_axi_gmem0_BUSER,
        sext_ln111_1 => trunc_ln_reg_185,
        local_buffer_0_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_0_address0,
        local_buffer_0_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_0_ce0,
        local_buffer_0_q0 => local_buffer_0_q0,
        local_buffer_1_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_1_address0,
        local_buffer_1_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_1_ce0,
        local_buffer_1_q0 => local_buffer_1_q0,
        local_buffer_2_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_2_address0,
        local_buffer_2_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_2_ce0,
        local_buffer_2_q0 => local_buffer_2_q0,
        local_buffer_3_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_3_address0,
        local_buffer_3_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_3_ce0,
        local_buffer_3_q0 => local_buffer_3_q0,
        local_buffer_4_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_4_address0,
        local_buffer_4_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_4_ce0,
        local_buffer_4_q0 => local_buffer_4_q0,
        local_buffer_5_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_5_address0,
        local_buffer_5_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_5_ce0,
        local_buffer_5_q0 => local_buffer_5_q0,
        local_buffer_6_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_6_address0,
        local_buffer_6_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_6_ce0,
        local_buffer_6_q0 => local_buffer_6_q0,
        local_buffer_7_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_7_address0,
        local_buffer_7_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_7_ce0,
        local_buffer_7_q0 => local_buffer_7_q0,
        local_buffer_8_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_8_address0,
        local_buffer_8_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_8_ce0,
        local_buffer_8_q0 => local_buffer_8_q0,
        local_buffer_9_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_9_address0,
        local_buffer_9_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_9_ce0,
        local_buffer_9_q0 => local_buffer_9_q0,
        local_buffer_10_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_10_address0,
        local_buffer_10_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_10_ce0,
        local_buffer_10_q0 => local_buffer_10_q0,
        local_buffer_11_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_11_address0,
        local_buffer_11_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_11_ce0,
        local_buffer_11_q0 => local_buffer_11_q0,
        local_buffer_12_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_12_address0,
        local_buffer_12_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_12_ce0,
        local_buffer_12_q0 => local_buffer_12_q0,
        local_buffer_13_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_13_address0,
        local_buffer_13_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_13_ce0,
        local_buffer_13_q0 => local_buffer_13_q0,
        local_buffer_14_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_14_address0,
        local_buffer_14_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_14_ce0,
        local_buffer_14_q0 => local_buffer_14_q0,
        local_buffer_15_address0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_15_address0,
        local_buffer_15_ce0 => grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_15_ce0,
        local_buffer_15_q0 => local_buffer_15_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_ready = ap_const_logic_1)) then 
                    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                trunc_ln_reg_185 <= add_ln111_fu_159_p2(63 downto 5);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, m_axi_gmem0_AWREADY, m_axi_gmem0_BVALID, ap_CS_fsm_state2, ap_CS_fsm_state9, grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (m_axi_gmem0_AWREADY = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (m_axi_gmem0_BVALID = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    add_ln111_fu_159_p2 <= std_logic_vector(signed(sext_ln111_fu_155_p1) + signed(dram_matrix));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(m_axi_gmem0_AWREADY)
    begin
        if ((m_axi_gmem0_AWREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_done)
    begin
        if ((grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(m_axi_gmem0_BVALID)
    begin
        if ((m_axi_gmem0_BVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_gmem0_BVALID, ap_CS_fsm_state9)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (m_axi_gmem0_BVALID = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(m_axi_gmem0_BVALID, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) and (m_axi_gmem0_BVALID = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    gmem0_blk_n_AW_assign_proc : process(m_axi_gmem0_AWREADY, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            gmem0_blk_n_AW <= m_axi_gmem0_AWREADY;
        else 
            gmem0_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem0_blk_n_B_assign_proc : process(m_axi_gmem0_BVALID, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            gmem0_blk_n_B <= m_axi_gmem0_BVALID;
        else 
            gmem0_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;

    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start_reg;
    local_buffer_0_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_0_address0;
    local_buffer_0_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_0_ce0;
    local_buffer_10_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_10_address0;
    local_buffer_10_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_10_ce0;
    local_buffer_11_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_11_address0;
    local_buffer_11_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_11_ce0;
    local_buffer_12_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_12_address0;
    local_buffer_12_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_12_ce0;
    local_buffer_13_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_13_address0;
    local_buffer_13_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_13_ce0;
    local_buffer_14_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_14_address0;
    local_buffer_14_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_14_ce0;
    local_buffer_15_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_15_address0;
    local_buffer_15_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_15_ce0;
    local_buffer_1_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_1_address0;
    local_buffer_1_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_1_ce0;
    local_buffer_2_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_2_address0;
    local_buffer_2_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_2_ce0;
    local_buffer_3_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_3_address0;
    local_buffer_3_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_3_ce0;
    local_buffer_4_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_4_address0;
    local_buffer_4_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_4_ce0;
    local_buffer_5_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_5_address0;
    local_buffer_5_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_5_ce0;
    local_buffer_6_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_6_address0;
    local_buffer_6_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_6_ce0;
    local_buffer_7_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_7_address0;
    local_buffer_7_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_7_ce0;
    local_buffer_8_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_8_address0;
    local_buffer_8_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_8_ce0;
    local_buffer_9_address0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_9_address0;
    local_buffer_9_ce0 <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_9_ce0;
    m_axi_gmem0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_ARVALID <= ap_const_logic_0;

    m_axi_gmem0_AWADDR_assign_proc : process(m_axi_gmem0_AWREADY, ap_CS_fsm_state2, grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWADDR, ap_CS_fsm_state3, ap_CS_fsm_state4, sext_ln111_1_fu_175_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (m_axi_gmem0_AWREADY = ap_const_logic_1))) then 
            m_axi_gmem0_AWADDR <= sext_ln111_1_fu_175_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem0_AWADDR <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWADDR;
        else 
            m_axi_gmem0_AWADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem0_AWBURST_assign_proc : process(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWBURST, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem0_AWBURST <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWBURST;
        else 
            m_axi_gmem0_AWBURST <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem0_AWCACHE_assign_proc : process(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWCACHE, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem0_AWCACHE <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWCACHE;
        else 
            m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem0_AWID_assign_proc : process(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWID, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem0_AWID <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWID;
        else 
            m_axi_gmem0_AWID <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem0_AWLEN_assign_proc : process(m_axi_gmem0_AWREADY, ap_CS_fsm_state2, grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWLEN, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (m_axi_gmem0_AWREADY = ap_const_logic_1))) then 
            m_axi_gmem0_AWLEN <= ap_const_lv32_80;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem0_AWLEN <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWLEN;
        else 
            m_axi_gmem0_AWLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem0_AWLOCK_assign_proc : process(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWLOCK, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem0_AWLOCK <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWLOCK;
        else 
            m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem0_AWPROT_assign_proc : process(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWPROT, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem0_AWPROT <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWPROT;
        else 
            m_axi_gmem0_AWPROT <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem0_AWQOS_assign_proc : process(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWQOS, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem0_AWQOS <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWQOS;
        else 
            m_axi_gmem0_AWQOS <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem0_AWREGION_assign_proc : process(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWREGION, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem0_AWREGION <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWREGION;
        else 
            m_axi_gmem0_AWREGION <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem0_AWSIZE_assign_proc : process(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWSIZE, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem0_AWSIZE <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWSIZE;
        else 
            m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem0_AWUSER_assign_proc : process(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWUSER, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem0_AWUSER <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWUSER;
        else 
            m_axi_gmem0_AWUSER <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem0_AWVALID_assign_proc : process(m_axi_gmem0_AWREADY, ap_CS_fsm_state2, grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWVALID, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (m_axi_gmem0_AWREADY = ap_const_logic_1))) then 
            m_axi_gmem0_AWVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem0_AWVALID <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWVALID;
        else 
            m_axi_gmem0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem0_BREADY_assign_proc : process(m_axi_gmem0_BVALID, ap_CS_fsm_state9, grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_BREADY, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) and (m_axi_gmem0_BVALID = ap_const_logic_1))) then 
            m_axi_gmem0_BREADY <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem0_BREADY <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_BREADY;
        else 
            m_axi_gmem0_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_RREADY <= ap_const_logic_0;
    m_axi_gmem0_WDATA <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WDATA;
    m_axi_gmem0_WID <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WID;
    m_axi_gmem0_WLAST <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WLAST;
    m_axi_gmem0_WSTRB <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WSTRB;
    m_axi_gmem0_WUSER <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WUSER;

    m_axi_gmem0_WVALID_assign_proc : process(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WVALID, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_gmem0_WVALID <= grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WVALID;
        else 
            m_axi_gmem0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln111_1_fu_175_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_185),64));

        sext_ln111_fu_155_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_147_p3),64));

    shl_ln_fu_147_p3 <= (tile_index & ap_const_lv12_0);
end behav;
