// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pipelined_layer_processor_write_big_tile_Pipeline_Write_Rows_Write_Cols (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        sext_ln111_1,
        local_buffer_0_address0,
        local_buffer_0_ce0,
        local_buffer_0_q0,
        local_buffer_1_address0,
        local_buffer_1_ce0,
        local_buffer_1_q0,
        local_buffer_2_address0,
        local_buffer_2_ce0,
        local_buffer_2_q0,
        local_buffer_3_address0,
        local_buffer_3_ce0,
        local_buffer_3_q0,
        local_buffer_4_address0,
        local_buffer_4_ce0,
        local_buffer_4_q0,
        local_buffer_5_address0,
        local_buffer_5_ce0,
        local_buffer_5_q0,
        local_buffer_6_address0,
        local_buffer_6_ce0,
        local_buffer_6_q0,
        local_buffer_7_address0,
        local_buffer_7_ce0,
        local_buffer_7_q0,
        local_buffer_8_address0,
        local_buffer_8_ce0,
        local_buffer_8_q0,
        local_buffer_9_address0,
        local_buffer_9_ce0,
        local_buffer_9_q0,
        local_buffer_10_address0,
        local_buffer_10_ce0,
        local_buffer_10_q0,
        local_buffer_11_address0,
        local_buffer_11_ce0,
        local_buffer_11_q0,
        local_buffer_12_address0,
        local_buffer_12_ce0,
        local_buffer_12_q0,
        local_buffer_13_address0,
        local_buffer_13_ce0,
        local_buffer_13_q0,
        local_buffer_14_address0,
        local_buffer_14_ce0,
        local_buffer_14_q0,
        local_buffer_15_address0,
        local_buffer_15_ce0,
        local_buffer_15_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [255:0] m_axi_gmem0_WDATA;
output  [31:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [255:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [58:0] sext_ln111_1;
output  [5:0] local_buffer_0_address0;
output   local_buffer_0_ce0;
input  [31:0] local_buffer_0_q0;
output  [5:0] local_buffer_1_address0;
output   local_buffer_1_ce0;
input  [31:0] local_buffer_1_q0;
output  [5:0] local_buffer_2_address0;
output   local_buffer_2_ce0;
input  [31:0] local_buffer_2_q0;
output  [5:0] local_buffer_3_address0;
output   local_buffer_3_ce0;
input  [31:0] local_buffer_3_q0;
output  [5:0] local_buffer_4_address0;
output   local_buffer_4_ce0;
input  [31:0] local_buffer_4_q0;
output  [5:0] local_buffer_5_address0;
output   local_buffer_5_ce0;
input  [31:0] local_buffer_5_q0;
output  [5:0] local_buffer_6_address0;
output   local_buffer_6_ce0;
input  [31:0] local_buffer_6_q0;
output  [5:0] local_buffer_7_address0;
output   local_buffer_7_ce0;
input  [31:0] local_buffer_7_q0;
output  [5:0] local_buffer_8_address0;
output   local_buffer_8_ce0;
input  [31:0] local_buffer_8_q0;
output  [5:0] local_buffer_9_address0;
output   local_buffer_9_ce0;
input  [31:0] local_buffer_9_q0;
output  [5:0] local_buffer_10_address0;
output   local_buffer_10_ce0;
input  [31:0] local_buffer_10_q0;
output  [5:0] local_buffer_11_address0;
output   local_buffer_11_ce0;
input  [31:0] local_buffer_11_q0;
output  [5:0] local_buffer_12_address0;
output   local_buffer_12_ce0;
input  [31:0] local_buffer_12_q0;
output  [5:0] local_buffer_13_address0;
output   local_buffer_13_ce0;
input  [31:0] local_buffer_13_q0;
output  [5:0] local_buffer_14_address0;
output   local_buffer_14_ce0;
input  [31:0] local_buffer_14_q0;
output  [5:0] local_buffer_15_address0;
output   local_buffer_15_ce0;
input  [31:0] local_buffer_15_q0;

reg ap_idle;
reg m_axi_gmem0_WVALID;
reg local_buffer_0_ce0;
reg local_buffer_1_ce0;
reg local_buffer_2_ce0;
reg local_buffer_3_ce0;
reg local_buffer_4_ce0;
reg local_buffer_5_ce0;
reg local_buffer_6_ce0;
reg local_buffer_7_ce0;
reg local_buffer_8_ce0;
reg local_buffer_9_ce0;
reg local_buffer_10_ce0;
reg local_buffer_11_ce0;
reg local_buffer_12_ce0;
reg local_buffer_13_ce0;
reg local_buffer_14_ce0;
reg local_buffer_15_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln111_fu_375_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_W;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln111_reg_621;
wire   [0:0] icmp_ln186_fu_468_p2;
reg   [0:0] icmp_ln186_reg_705;
wire   [31:0] select_ln186_fu_519_p3;
reg   [31:0] select_ln186_reg_722;
wire   [31:0] select_ln186_1_fu_526_p3;
reg   [31:0] select_ln186_1_reg_727;
wire   [31:0] select_ln186_2_fu_533_p3;
reg   [31:0] select_ln186_2_reg_732;
wire   [31:0] select_ln186_3_fu_540_p3;
reg   [31:0] select_ln186_3_reg_737;
wire   [31:0] select_ln186_4_fu_547_p3;
reg   [31:0] select_ln186_4_reg_742;
wire   [31:0] select_ln186_5_fu_554_p3;
reg   [31:0] select_ln186_5_reg_747;
wire   [31:0] select_ln186_6_fu_561_p3;
reg   [31:0] select_ln186_6_reg_752;
wire   [31:0] select_ln186_7_fu_568_p3;
reg   [31:0] select_ln186_7_reg_757;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln186_fu_444_p1;
wire    ap_block_pp0_stage0_01001;
reg   [5:0] c_fu_110;
wire   [5:0] add_ln112_fu_474_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_c_load;
reg   [2:0] indvar_fu_114;
wire   [2:0] select_ln112_fu_486_p3;
reg   [2:0] ap_sig_allocacmp_indvar_load;
reg   [5:0] r_fu_118;
wire   [5:0] select_ln111_1_fu_416_p3;
reg   [5:0] ap_sig_allocacmp_r_load;
reg   [7:0] indvar_flatten_fu_122;
wire   [7:0] add_ln111_fu_381_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [0:0] icmp_ln112_fu_402_p2;
wire   [5:0] add_ln111_1_fu_396_p2;
wire   [5:0] select_ln111_fu_408_p3;
wire   [4:0] trunc_ln113_fu_424_p1;
wire   [0:0] tmp_1_fu_428_p3;
wire   [5:0] tmp_fu_436_p3;
wire   [3:0] trunc_ln186_fu_464_p1;
wire   [2:0] add_ln112_1_fu_480_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

pipelined_layer_processor_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_375_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_110 <= add_ln112_fu_474_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_110 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_375_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_122 <= add_ln111_fu_381_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_122 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_375_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_fu_114 <= select_ln112_fu_486_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_fu_114 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_375_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            r_fu_118 <= select_ln111_1_fu_416_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_118 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln111_reg_621 <= icmp_ln111_fu_375_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln111_fu_375_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln186_reg_705 <= icmp_ln186_fu_468_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln111_reg_621 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln186_1_reg_727 <= select_ln186_1_fu_526_p3;
        select_ln186_2_reg_732 <= select_ln186_2_fu_533_p3;
        select_ln186_3_reg_737 <= select_ln186_3_fu_540_p3;
        select_ln186_4_reg_742 <= select_ln186_4_fu_547_p3;
        select_ln186_5_reg_747 <= select_ln186_5_fu_554_p3;
        select_ln186_6_reg_752 <= select_ln186_6_fu_561_p3;
        select_ln186_7_reg_757 <= select_ln186_7_fu_568_p3;
        select_ln186_reg_722 <= select_ln186_fu_519_p3;
    end
end

always @ (*) begin
    if (((icmp_ln111_fu_375_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln111_reg_621 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 6'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_110;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_122;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_load = 3'd0;
    end else begin
        ap_sig_allocacmp_indvar_load = indvar_fu_114;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_r_load = 6'd0;
    end else begin
        ap_sig_allocacmp_r_load = r_fu_118;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gmem0_blk_n_W = m_axi_gmem0_WREADY;
    end else begin
        gmem0_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_0_ce0 = 1'b1;
    end else begin
        local_buffer_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_10_ce0 = 1'b1;
    end else begin
        local_buffer_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_11_ce0 = 1'b1;
    end else begin
        local_buffer_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_12_ce0 = 1'b1;
    end else begin
        local_buffer_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_13_ce0 = 1'b1;
    end else begin
        local_buffer_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_14_ce0 = 1'b1;
    end else begin
        local_buffer_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_15_ce0 = 1'b1;
    end else begin
        local_buffer_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_1_ce0 = 1'b1;
    end else begin
        local_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_2_ce0 = 1'b1;
    end else begin
        local_buffer_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_3_ce0 = 1'b1;
    end else begin
        local_buffer_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_4_ce0 = 1'b1;
    end else begin
        local_buffer_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_5_ce0 = 1'b1;
    end else begin
        local_buffer_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_6_ce0 = 1'b1;
    end else begin
        local_buffer_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_7_ce0 = 1'b1;
    end else begin
        local_buffer_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_8_ce0 = 1'b1;
    end else begin
        local_buffer_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_buffer_9_ce0 = 1'b1;
    end else begin
        local_buffer_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m_axi_gmem0_WVALID = 1'b1;
    end else begin
        m_axi_gmem0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln111_1_fu_396_p2 = (ap_sig_allocacmp_r_load + 6'd1);

assign add_ln111_fu_381_p2 = (ap_sig_allocacmp_indvar_flatten_load + 8'd1);

assign add_ln112_1_fu_480_p2 = (ap_sig_allocacmp_indvar_load + 3'd1);

assign add_ln112_fu_474_p2 = (select_ln111_fu_408_p3 + 6'd8);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln111_fu_375_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln112_fu_402_p2 = ((ap_sig_allocacmp_indvar_load == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln186_fu_468_p2 = ((trunc_ln186_fu_464_p1 == 4'd8) ? 1'b1 : 1'b0);

assign local_buffer_0_address0 = zext_ln186_fu_444_p1;

assign local_buffer_10_address0 = zext_ln186_fu_444_p1;

assign local_buffer_11_address0 = zext_ln186_fu_444_p1;

assign local_buffer_12_address0 = zext_ln186_fu_444_p1;

assign local_buffer_13_address0 = zext_ln186_fu_444_p1;

assign local_buffer_14_address0 = zext_ln186_fu_444_p1;

assign local_buffer_15_address0 = zext_ln186_fu_444_p1;

assign local_buffer_1_address0 = zext_ln186_fu_444_p1;

assign local_buffer_2_address0 = zext_ln186_fu_444_p1;

assign local_buffer_3_address0 = zext_ln186_fu_444_p1;

assign local_buffer_4_address0 = zext_ln186_fu_444_p1;

assign local_buffer_5_address0 = zext_ln186_fu_444_p1;

assign local_buffer_6_address0 = zext_ln186_fu_444_p1;

assign local_buffer_7_address0 = zext_ln186_fu_444_p1;

assign local_buffer_8_address0 = zext_ln186_fu_444_p1;

assign local_buffer_9_address0 = zext_ln186_fu_444_p1;

assign m_axi_gmem0_ARADDR = 64'd0;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 32'd0;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_ARVALID = 1'b0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_RREADY = 1'b0;

assign m_axi_gmem0_WDATA = {{{{{{{{select_ln186_7_reg_757}, {select_ln186_6_reg_752}}, {select_ln186_5_reg_747}}, {select_ln186_4_reg_742}}, {select_ln186_3_reg_737}}, {select_ln186_2_reg_732}}, {select_ln186_1_reg_727}}, {select_ln186_reg_722}};

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 32'd4294967295;

assign m_axi_gmem0_WUSER = 1'd0;

assign select_ln111_1_fu_416_p3 = ((icmp_ln112_fu_402_p2[0:0] == 1'b1) ? add_ln111_1_fu_396_p2 : ap_sig_allocacmp_r_load);

assign select_ln111_fu_408_p3 = ((icmp_ln112_fu_402_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_c_load);

assign select_ln112_fu_486_p3 = ((icmp_ln112_fu_402_p2[0:0] == 1'b1) ? 3'd1 : add_ln112_1_fu_480_p2);

assign select_ln186_1_fu_526_p3 = ((icmp_ln186_reg_705[0:0] == 1'b1) ? local_buffer_9_q0 : local_buffer_1_q0);

assign select_ln186_2_fu_533_p3 = ((icmp_ln186_reg_705[0:0] == 1'b1) ? local_buffer_10_q0 : local_buffer_2_q0);

assign select_ln186_3_fu_540_p3 = ((icmp_ln186_reg_705[0:0] == 1'b1) ? local_buffer_11_q0 : local_buffer_3_q0);

assign select_ln186_4_fu_547_p3 = ((icmp_ln186_reg_705[0:0] == 1'b1) ? local_buffer_12_q0 : local_buffer_4_q0);

assign select_ln186_5_fu_554_p3 = ((icmp_ln186_reg_705[0:0] == 1'b1) ? local_buffer_13_q0 : local_buffer_5_q0);

assign select_ln186_6_fu_561_p3 = ((icmp_ln186_reg_705[0:0] == 1'b1) ? local_buffer_14_q0 : local_buffer_6_q0);

assign select_ln186_7_fu_568_p3 = ((icmp_ln186_reg_705[0:0] == 1'b1) ? local_buffer_15_q0 : local_buffer_7_q0);

assign select_ln186_fu_519_p3 = ((icmp_ln186_reg_705[0:0] == 1'b1) ? local_buffer_8_q0 : local_buffer_0_q0);

assign tmp_1_fu_428_p3 = select_ln111_fu_408_p3[32'd4];

assign tmp_fu_436_p3 = {{trunc_ln113_fu_424_p1}, {tmp_1_fu_428_p3}};

assign trunc_ln113_fu_424_p1 = select_ln111_1_fu_416_p3[4:0];

assign trunc_ln186_fu_464_p1 = select_ln111_fu_408_p3[3:0];

assign zext_ln186_fu_444_p1 = tmp_fu_436_p3;

endmodule //pipelined_layer_processor_write_big_tile_Pipeline_Write_Rows_Write_Cols
