// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pipelined_layer_processor_write_big_tile (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        local_buffer_0_address0,
        local_buffer_0_ce0,
        local_buffer_0_q0,
        local_buffer_1_address0,
        local_buffer_1_ce0,
        local_buffer_1_q0,
        local_buffer_2_address0,
        local_buffer_2_ce0,
        local_buffer_2_q0,
        local_buffer_3_address0,
        local_buffer_3_ce0,
        local_buffer_3_q0,
        local_buffer_4_address0,
        local_buffer_4_ce0,
        local_buffer_4_q0,
        local_buffer_5_address0,
        local_buffer_5_ce0,
        local_buffer_5_q0,
        local_buffer_6_address0,
        local_buffer_6_ce0,
        local_buffer_6_q0,
        local_buffer_7_address0,
        local_buffer_7_ce0,
        local_buffer_7_q0,
        local_buffer_8_address0,
        local_buffer_8_ce0,
        local_buffer_8_q0,
        local_buffer_9_address0,
        local_buffer_9_ce0,
        local_buffer_9_q0,
        local_buffer_10_address0,
        local_buffer_10_ce0,
        local_buffer_10_q0,
        local_buffer_11_address0,
        local_buffer_11_ce0,
        local_buffer_11_q0,
        local_buffer_12_address0,
        local_buffer_12_ce0,
        local_buffer_12_q0,
        local_buffer_13_address0,
        local_buffer_13_ce0,
        local_buffer_13_q0,
        local_buffer_14_address0,
        local_buffer_14_ce0,
        local_buffer_14_q0,
        local_buffer_15_address0,
        local_buffer_15_ce0,
        local_buffer_15_q0,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        dram_matrix,
        tile_index
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] local_buffer_0_address0;
output   local_buffer_0_ce0;
input  [31:0] local_buffer_0_q0;
output  [5:0] local_buffer_1_address0;
output   local_buffer_1_ce0;
input  [31:0] local_buffer_1_q0;
output  [5:0] local_buffer_2_address0;
output   local_buffer_2_ce0;
input  [31:0] local_buffer_2_q0;
output  [5:0] local_buffer_3_address0;
output   local_buffer_3_ce0;
input  [31:0] local_buffer_3_q0;
output  [5:0] local_buffer_4_address0;
output   local_buffer_4_ce0;
input  [31:0] local_buffer_4_q0;
output  [5:0] local_buffer_5_address0;
output   local_buffer_5_ce0;
input  [31:0] local_buffer_5_q0;
output  [5:0] local_buffer_6_address0;
output   local_buffer_6_ce0;
input  [31:0] local_buffer_6_q0;
output  [5:0] local_buffer_7_address0;
output   local_buffer_7_ce0;
input  [31:0] local_buffer_7_q0;
output  [5:0] local_buffer_8_address0;
output   local_buffer_8_ce0;
input  [31:0] local_buffer_8_q0;
output  [5:0] local_buffer_9_address0;
output   local_buffer_9_ce0;
input  [31:0] local_buffer_9_q0;
output  [5:0] local_buffer_10_address0;
output   local_buffer_10_ce0;
input  [31:0] local_buffer_10_q0;
output  [5:0] local_buffer_11_address0;
output   local_buffer_11_ce0;
input  [31:0] local_buffer_11_q0;
output  [5:0] local_buffer_12_address0;
output   local_buffer_12_ce0;
input  [31:0] local_buffer_12_q0;
output  [5:0] local_buffer_13_address0;
output   local_buffer_13_ce0;
input  [31:0] local_buffer_13_q0;
output  [5:0] local_buffer_14_address0;
output   local_buffer_14_ce0;
input  [31:0] local_buffer_14_q0;
output  [5:0] local_buffer_15_address0;
output   local_buffer_15_ce0;
input  [31:0] local_buffer_15_q0;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [255:0] m_axi_gmem0_WDATA;
output  [31:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [255:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [63:0] dram_matrix;
input  [24:0] tile_index;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem0_AWVALID;
reg[63:0] m_axi_gmem0_AWADDR;
reg[0:0] m_axi_gmem0_AWID;
reg[31:0] m_axi_gmem0_AWLEN;
reg[2:0] m_axi_gmem0_AWSIZE;
reg[1:0] m_axi_gmem0_AWBURST;
reg[1:0] m_axi_gmem0_AWLOCK;
reg[3:0] m_axi_gmem0_AWCACHE;
reg[2:0] m_axi_gmem0_AWPROT;
reg[3:0] m_axi_gmem0_AWQOS;
reg[3:0] m_axi_gmem0_AWREGION;
reg[0:0] m_axi_gmem0_AWUSER;
reg m_axi_gmem0_WVALID;
reg m_axi_gmem0_BREADY;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem0_blk_n_AW;
wire    ap_CS_fsm_state2;
reg    gmem0_blk_n_B;
wire    ap_CS_fsm_state9;
reg   [58:0] trunc_ln_reg_185;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_done;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_idle;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_ready;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWVALID;
wire   [63:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWADDR;
wire   [0:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWID;
wire   [31:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWLEN;
wire   [2:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWBURST;
wire   [1:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWPROT;
wire   [3:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWQOS;
wire   [3:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWREGION;
wire   [0:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWUSER;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WVALID;
wire   [255:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WDATA;
wire   [31:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WSTRB;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WLAST;
wire   [0:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WID;
wire   [0:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WUSER;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARVALID;
wire   [63:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARADDR;
wire   [0:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARID;
wire   [31:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARLEN;
wire   [2:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARBURST;
wire   [1:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARPROT;
wire   [3:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARQOS;
wire   [3:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARREGION;
wire   [0:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARUSER;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_RREADY;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_BREADY;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_0_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_0_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_1_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_1_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_2_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_2_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_3_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_3_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_4_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_4_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_5_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_5_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_6_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_6_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_7_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_7_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_8_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_8_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_9_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_9_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_10_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_10_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_11_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_11_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_12_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_12_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_13_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_13_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_14_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_14_ce0;
wire   [5:0] grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_15_address0;
wire    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_15_ce0;
reg    grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire  signed [63:0] sext_ln111_1_fu_175_p1;
wire   [36:0] shl_ln_fu_147_p3;
wire  signed [63:0] sext_ln111_fu_155_p1;
wire   [63:0] add_ln111_fu_159_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start_reg = 1'b0;
end

pipelined_layer_processor_write_big_tile_Pipeline_Write_Rows_Write_Cols grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start),
    .ap_done(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_done),
    .ap_idle(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_idle),
    .ap_ready(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_ready),
    .m_axi_gmem0_AWVALID(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(m_axi_gmem0_AWREADY),
    .m_axi_gmem0_AWADDR(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(m_axi_gmem0_WREADY),
    .m_axi_gmem0_WDATA(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(1'b0),
    .m_axi_gmem0_ARADDR(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(1'b0),
    .m_axi_gmem0_RREADY(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(256'd0),
    .m_axi_gmem0_RLAST(1'b0),
    .m_axi_gmem0_RID(1'd0),
    .m_axi_gmem0_RFIFONUM(9'd0),
    .m_axi_gmem0_RUSER(1'd0),
    .m_axi_gmem0_RRESP(2'd0),
    .m_axi_gmem0_BVALID(m_axi_gmem0_BVALID),
    .m_axi_gmem0_BREADY(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(m_axi_gmem0_BRESP),
    .m_axi_gmem0_BID(m_axi_gmem0_BID),
    .m_axi_gmem0_BUSER(m_axi_gmem0_BUSER),
    .sext_ln111_1(trunc_ln_reg_185),
    .local_buffer_0_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_0_address0),
    .local_buffer_0_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_0_ce0),
    .local_buffer_0_q0(local_buffer_0_q0),
    .local_buffer_1_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_1_address0),
    .local_buffer_1_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_1_ce0),
    .local_buffer_1_q0(local_buffer_1_q0),
    .local_buffer_2_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_2_address0),
    .local_buffer_2_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_2_ce0),
    .local_buffer_2_q0(local_buffer_2_q0),
    .local_buffer_3_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_3_address0),
    .local_buffer_3_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_3_ce0),
    .local_buffer_3_q0(local_buffer_3_q0),
    .local_buffer_4_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_4_address0),
    .local_buffer_4_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_4_ce0),
    .local_buffer_4_q0(local_buffer_4_q0),
    .local_buffer_5_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_5_address0),
    .local_buffer_5_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_5_ce0),
    .local_buffer_5_q0(local_buffer_5_q0),
    .local_buffer_6_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_6_address0),
    .local_buffer_6_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_6_ce0),
    .local_buffer_6_q0(local_buffer_6_q0),
    .local_buffer_7_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_7_address0),
    .local_buffer_7_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_7_ce0),
    .local_buffer_7_q0(local_buffer_7_q0),
    .local_buffer_8_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_8_address0),
    .local_buffer_8_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_8_ce0),
    .local_buffer_8_q0(local_buffer_8_q0),
    .local_buffer_9_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_9_address0),
    .local_buffer_9_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_9_ce0),
    .local_buffer_9_q0(local_buffer_9_q0),
    .local_buffer_10_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_10_address0),
    .local_buffer_10_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_10_ce0),
    .local_buffer_10_q0(local_buffer_10_q0),
    .local_buffer_11_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_11_address0),
    .local_buffer_11_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_11_ce0),
    .local_buffer_11_q0(local_buffer_11_q0),
    .local_buffer_12_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_12_address0),
    .local_buffer_12_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_12_ce0),
    .local_buffer_12_q0(local_buffer_12_q0),
    .local_buffer_13_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_13_address0),
    .local_buffer_13_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_13_ce0),
    .local_buffer_13_q0(local_buffer_13_q0),
    .local_buffer_14_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_14_address0),
    .local_buffer_14_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_14_ce0),
    .local_buffer_14_q0(local_buffer_14_q0),
    .local_buffer_15_address0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_15_address0),
    .local_buffer_15_ce0(grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_15_ce0),
    .local_buffer_15_q0(local_buffer_15_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start_reg <= 1'b1;
        end else if ((grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_ready == 1'b1)) begin
            grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln_reg_185 <= {{add_ln111_fu_159_p2[63:5]}};
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem0_BVALID == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state9) & (m_axi_gmem0_BVALID == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (m_axi_gmem0_BVALID == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem0_blk_n_AW = m_axi_gmem0_AWREADY;
    end else begin
        gmem0_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        gmem0_blk_n_B = m_axi_gmem0_BVALID;
    end else begin
        gmem0_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (m_axi_gmem0_AWREADY == 1'b1))) begin
        m_axi_gmem0_AWADDR = sext_ln111_1_fu_175_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem0_AWADDR = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWADDR;
    end else begin
        m_axi_gmem0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem0_AWBURST = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWBURST;
    end else begin
        m_axi_gmem0_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem0_AWCACHE = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWCACHE;
    end else begin
        m_axi_gmem0_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem0_AWID = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWID;
    end else begin
        m_axi_gmem0_AWID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (m_axi_gmem0_AWREADY == 1'b1))) begin
        m_axi_gmem0_AWLEN = 32'd128;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem0_AWLEN = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWLEN;
    end else begin
        m_axi_gmem0_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem0_AWLOCK = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWLOCK;
    end else begin
        m_axi_gmem0_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem0_AWPROT = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWPROT;
    end else begin
        m_axi_gmem0_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem0_AWQOS = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWQOS;
    end else begin
        m_axi_gmem0_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem0_AWREGION = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWREGION;
    end else begin
        m_axi_gmem0_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem0_AWSIZE = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWSIZE;
    end else begin
        m_axi_gmem0_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem0_AWUSER = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWUSER;
    end else begin
        m_axi_gmem0_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (m_axi_gmem0_AWREADY == 1'b1))) begin
        m_axi_gmem0_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem0_AWVALID = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_AWVALID;
    end else begin
        m_axi_gmem0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (m_axi_gmem0_BVALID == 1'b1))) begin
        m_axi_gmem0_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem0_BREADY = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_BREADY;
    end else begin
        m_axi_gmem0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem0_WVALID = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WVALID;
    end else begin
        m_axi_gmem0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (m_axi_gmem0_AWREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (m_axi_gmem0_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln111_fu_159_p2 = ($signed(sext_ln111_fu_155_p1) + $signed(dram_matrix));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_ap_start_reg;

assign local_buffer_0_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_0_address0;

assign local_buffer_0_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_0_ce0;

assign local_buffer_10_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_10_address0;

assign local_buffer_10_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_10_ce0;

assign local_buffer_11_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_11_address0;

assign local_buffer_11_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_11_ce0;

assign local_buffer_12_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_12_address0;

assign local_buffer_12_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_12_ce0;

assign local_buffer_13_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_13_address0;

assign local_buffer_13_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_13_ce0;

assign local_buffer_14_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_14_address0;

assign local_buffer_14_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_14_ce0;

assign local_buffer_15_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_15_address0;

assign local_buffer_15_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_15_ce0;

assign local_buffer_1_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_1_address0;

assign local_buffer_1_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_1_ce0;

assign local_buffer_2_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_2_address0;

assign local_buffer_2_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_2_ce0;

assign local_buffer_3_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_3_address0;

assign local_buffer_3_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_3_ce0;

assign local_buffer_4_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_4_address0;

assign local_buffer_4_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_4_ce0;

assign local_buffer_5_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_5_address0;

assign local_buffer_5_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_5_ce0;

assign local_buffer_6_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_6_address0;

assign local_buffer_6_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_6_ce0;

assign local_buffer_7_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_7_address0;

assign local_buffer_7_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_7_ce0;

assign local_buffer_8_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_8_address0;

assign local_buffer_8_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_8_ce0;

assign local_buffer_9_address0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_9_address0;

assign local_buffer_9_ce0 = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_local_buffer_9_ce0;

assign m_axi_gmem0_ARADDR = 64'd0;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 32'd0;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_ARVALID = 1'b0;

assign m_axi_gmem0_RREADY = 1'b0;

assign m_axi_gmem0_WDATA = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WDATA;

assign m_axi_gmem0_WID = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WID;

assign m_axi_gmem0_WLAST = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WLAST;

assign m_axi_gmem0_WSTRB = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WSTRB;

assign m_axi_gmem0_WUSER = grp_write_big_tile_Pipeline_Write_Rows_Write_Cols_fu_108_m_axi_gmem0_WUSER;

assign sext_ln111_1_fu_175_p1 = $signed(trunc_ln_reg_185);

assign sext_ln111_fu_155_p1 = $signed(shl_ln_fu_147_p3);

assign shl_ln_fu_147_p3 = {{tile_index}, {12'd0}};

endmodule //pipelined_layer_processor_write_big_tile
